package common
const (
	// account
	C_LOGIN_REQUEST =1
	C_LOGIN_RESPOND =2

	C_LOGOUT_REQUEST =3
	C_LOGOUT_RESPOND =4

	C_QUERY_PLAYER_REQUEST =5
	C_QUERY_PLAYER_RESPOND =6

	C_CREATE_PLAYER_REQUEST =7
	C_CREATE_PLAYER_RESPOND =8

	// story
	C_STORY_FINISH_FIGHT_REQUEST =348
	C_STORY_FINISH_FIGHT_RESPOND =349

	// ai action
	NOTIFY_AI_ACTION =1105

	// guild
	C_GUILD_QUERY_APPLY_REQUEST =3016
	C_GUILD_QUERY_APPLY_RESPOND =3017

	C_GUILD_AUDIT_REQUEST =3018
	C_GUILD_AUDIT_RESPOND =3019

	C_GUILD_QUERY_GUILD_LIST_REQUEST =3008
	C_GUILD_QUERY_GUILD_LIST_RESPOND =3009

	C_GUILD_QUERY_MEMBERS_REQUEST =3010
	C_GUILD_QUERY_MEMBERS_RESPOND =3011

	C_GUILD_JOIN_REQUEST =3004
	C_GUILD_JOIN_RESPOND =3005

	C_GUILD_DONATE_REQUEST =3094
	C_GUILD_DONATE_RESPOND =3095

	C_GUILD_5XING_JOIN_REQUEST =3050
	C_GUILD_5XING_JOIN_RESPOND =3051

	// manor
	C_MANOR_ENTER_REQUEST =11001
	C_MANOR_ENTER_RESPOND =11002

	C_MANOR_LEAVE_REQUEST =11003
	C_MANOR_LEAVE_RESPOND =11004

	C_MANOR_QUERY_PLACEHOLDER_REQUEST =11005
	C_MANOR_QUERY_PLACEHOLDER_RESPOND =11006

	C_MANOR_PICK_TREASURE_REQUEST =11011
	C_MANOR_PICK_TREASURE_RESPOND =11012

	C_MANOR_GATHER_RESOURCE_REQUEST =11013
	C_MANOR_GATHER_RESOURCE_RESPOND =11014

	C_MANOR_UPGRADE_RESOURCE_REQUEST =11015
	C_MANOR_UPGRADE_RESOURCE_RESPOND =11016

	C_MANOR_ASSIST_RESOURCE_REQUEST = 11017
	C_MANOR_ASSIST_RESOURCE_RESPOND = 11018

	C_MANOR_PREPARE_ATTACK_MONSTER_REQUEST =11007
	C_MANOR_PREPARE_ATTACK_MONSTER_RESPOND =11008

	C_MANOR_CHECK_ATTACK_MONSTER_REQUEST =11009
	C_MANOR_CHECK_ATTACK_MONSTER_RESPOND =11010

	C_MANOR_ATTACK_BOSS_REQUEST = 11019
	C_MANOR_ATTACK_BOSS_RESPOND = 11020

	// arena
	C_ARENA_JOIN_REQUEST = 504
	C_ARENA_JOIN_RESPOND = 505

	C_ARENA_ATTACK_REQUEST =502
	C_ARENA_ATTACK_RESPOND =503

	// billboard

	// mail contact
	C_MAIL_CONTACT_GET_REQUEST =5011
	C_MAIL_CONTACT_GET_RESPOND =5012

	C_MAIL_CONTACT_ADD_REQUEST = 5013
	C_MAIL_CONTACT_ADD_RESPOND = 5014

	C_MAIL_CONTACT_RECOMMEND_REQUEST = 5021
	C_MAIL_CONTACT_RECOMMEND_RESPOND = 5022
)
const (
	RET_SUCCESS =0
	RET_ERROR =1
	RET_CHARACTER_NOT_EXIST =3
	RET_GUILD_NOT_EXIST =805
)

const(
	ACTION_LOGIN =1
	ACTION_LOGOUT =2

	ACTION_ARENA_ATTACK =3

	ACTION_GUILD_APPLY  =4
	ACTION_GUILD_DONATE =5
	ACTION_GUILD_JOIN_5XING =6

	ACTION_MANOR_ENTER =7
	ACTION_MANOR_LEAVE =8
	ACTION_MANOR_ATTACK_BOSS =9

	ACTION_SHOW_BILLBOARD =10
)
const(
	FLAG_MANOR_ENTER =1
	FLAG_MAIL_CONTACT_AUTO_ADD =2
)
const(
	MANOR_RESOURCE_LQ =1
	MANOR_RESOURCE_WJXD =2
	MANOR_RESOURCE_NC =3
	MANOR_RESOURCE_YB =4
)
const(
	MANOR_PLACEHOLDER_TYPE_BOSS =1
	MANOR_PLACEHOLDER_TYPE_MONSTER =2
	MANOR_PLACEHOLDER_TYPE_TREASURE =3
)
const(
	MANOR_HOME  =1 // 自己庄园
	MANOR_WORLD =3 // 世界boss庄园
)
const(
	MANOR_WORLD_BOSS_ID =9999999
)
