



61.219.16.18:20003 reward {"pid":100007,"reason":1040,"limit":0,"name":"降臨神將排行獎勵补偿","manual":true,"type":"reward","content":[{"type":"item","id":202001,"count":10},{"type":"item","id":240114,"count":5}]}


61.219.16.18:20003 reward {"pid":115204,"reason":1040,"limit":0,"name":"降臨神將排行獎勵补偿","manual":true,"type":"reward","content":[{"type":"item","id":202001,"count":10},{"type":"item","id":240114,"count":5}]}
61.219.16.18:20003 reward {"pid":115204,"reason":1040,"limit":0,"name":"降臨神將積分達值獎勵补偿","manual":true,"type":"reward","content":[{"type":"item","id":240204,"count":10}]}
61.219.16.31:20041 reward {"pid":104701,"reason":1040,"limit":0,"name":"降臨神將排行獎勵补偿","manual":true,"type":"reward","content":[{"type":"item","id":201012,"count":10},{"type":"item","id":240114,"count":5}]}
61.219.16.31:20039 reward {"pid":101582,"reason":1040,"limit":0,"name":"降臨神將排行獎勵补偿","manual":true,"type":"reward","content":[{"type":"item","id":202001,"count":10},{"type":"item","id":240114,"count":3}]}
61.219.16.27:20024 reward {"pid":100355,"reason":1040,"limit":0,"name":"降臨神將排行獎勵补偿","manual":true,"type":"reward","content":[{"type":"item","id":240114,"count":5}]}
61.219.16.19:20020 reward {"pid":102874,"reason":1040,"limit":0,"name":"降臨神將排行獎勵补偿","manual":true,"type":"reward","content":[{"type":"item","id":201012,"count":10},{"type":"item","id":240114,"count":5}]}


