#ifndef H_YQ_FRAMEWORK_COMMON_MACRO_H__
#define H_YQ_FRAMEWORK_COMMON_MACRO_H__

#define MAX_WORLD_COUNT 8
#define WORLD_DISPATCHER_PORT_BASE 9810
#define WORLD_PORT_BASE 9910
#define ROUTE_PORT_BASE 10010

#endif

