module "Command"

RET_SUCCESS = 0 --成功
RET_ERROR = 1 --一般错误
RET_EXIST = 2 --目标已经存在
RET_NOT_EXIST = 3 --目标不存在
RET_PARAM_ERROR = 4 --参数错误
RET_INPROGRESS = 5 --目标忙碌
RET_MAX_LEVEL = 6 --已经到达最大等级
RET_DEPEND = 7 --不满足依赖条件
RET_RESOURCES = 8 --资源不足
RET_FULL = 9 --容器已满
RET_NOT_ENOUGH = 10 --数量不足
RET_PREMISSIONS = 11 --权限不足
RET_COOLDOWN = 12 --cd中
RET_ALREADYAT = 13 -- 已经在 活动界面
RET_DATABASEERROR = 14 -- 存在更新失败的部分
RET_VIP_LEVEL_LIMIT = 15 -- VIP等级不足
RET_TARGET_NOT_EXIST = 50 -- 目标不存

RET_CHANNEL_INVALID = 51 -- 聊天频道错误
RET_LEVEL_NOT_ENOUGH = 52 -- 等级不足

RET_ARENA_COOLDOWN = 500 -- 排名竞技场战斗冷却

RET_CHARACTER_NOT_EXIST = RET_NOT_EXIST
RET_GUILD_EXIST  = 801
RET_GUILD_LEADER =  802
RET_GUILD_MEMBER =  803
RET_GUILD_NAME_EXIST = 804
RET_GUILD_NOT_EXIST = 805
RET_GUILD_PREMISSION =  806
RET_GUILD_PREMISSIONS =  807
RET_GUILD_REQUEST_INPROGRESS =  808
RET_GUILD_REQUEST_NOT_EXIST = 809
RET_GUILD_FULL  = 810
RET_GUILD_5XING_PLAYER_NOT_JOIN = 811
RET_GUILD_UNABLE_COP = 812 --现在不能进行人事变动
RET_GUILD_DEPEND_LEVEL = 813 -- 军团等级不足
RET_GUILD_UNABLE_JOIN = 814 -- 退出军团2小时内不能加入
RET_GUILD_WAR_ALREADY_JOIN = 815 -- 军团战已经加入
RET_GUILD_INVITE_USED = 816 --军团邀请被使用
RET_GUILD_5XING_PLAYER_NOT_JOIN = 811
RET_GUILD_TARGET_GUILD_NOT_EXIST = 812 -- 目标不存在军团
RET_GUILD_TARGET_GUILD_NOT_SAME = 813 -- 目标和玩家军团不一致
RET_MAX_HELP = 814 -- 祈愿帮助次数用完
RET_GUILD_PRAY_ALREADY_FINISHED = 817 -- 玩家已完成改项祈愿
RET_EXCHANGE_ERROR = 818 -- 交易失败
RET_GUILD_SAME_PID = 819 -- 军团祈愿pid和targetID相同 
RET_MAX_HELPED = 820 -- 祈愿求助次数用完
RET_GUILD_NEEDNT_HELP = 821 -- 玩家祈愿不需要协助
RET_EXPLORE_FINISH = 822  --军团探索已经完成
RET_NOT_ENEMY = 823 --竞技场没有匹配到对手
RET_ALREADY_HAS_TEAM = 824 -- 玩家已经加入其它小队
RET_ESCORT_TIME_OUT = 1006 -- 超时
RET_NOT_ONLINE = 1007 -- 玩家离线

LOGOUT_NORMAL =  0
LOGOUT_ANOTHER_LOGIN =  1
LOGOUT_ADDICTED =      2
LOGOUT_ADMIN_KICK =  3
LOGOUT_CONNECT =  4
LOGOUT_ADMIN_BAN =  5

NOTIFY_ACTION_BROADCAST = 10
--------------------------------------------------------------------------------
--
C_I_AM_GOD_REQEUST = 1000 --重置cd和资源最大化请求
-- [sn]
C_I_AM_GOD_RESPOND = 1001 --重置cd和资源最大化返回
-- [sn, result, info]

C_CALL_SCRIPT_REQUEST = 1002 -- 调用脚本请求
-- [sn, func, param, ...]
C_CALL_SCRIPT_RESPOND = 1003 -- 调用脚本返回
-- [sn, result]

S_SERVICE_REGISTER_REQUEST  = 1004  -- 注册服务 ServiceRegisterRequest
S_SERVICE_REGISTER_RESPOND  = 1005  -- 注册服务 ServiceRegisterRespond
    SERVICE_GATEWAY =   1
    SERVICE_WORLD   =   2
    SERVICE_CHAT    =   3

S_SERVICE_BROADCAST_REQUEST = 1006  -- 广播请求 ServiceBroadcastRequest
S_SERVICE_BROADCAST_RESPOND = 1007  -- 广播返回 ServiceBroadcastRespond


C_GET_SERVICE_STATUS_REQUEST    = 1008  -- 获取在线服务
-- [sn]

C_GET_SERVICE_STATUS_RESPOND    = 1009
-- [sn, result, id, ...]

S_ADMIN_ADD_ACTIVITY_INFO_REQUEST = 1010 -- PAdminAddActivityInfoRequest
S_ADMIN_ADD_ACTIVITY_INFO_RESPOND = 1011 -- GameRespond

S_ADMIN_ADD_ACHIEVEMENT_INFO_REQUEST = 1014 -- PAdminAddAchievementInfoRequest
S_ADMIN_ADD_ACHIEVEMENT_INFO_RESPOND = 1015 -- GameRespond

S_QUERY_PLAYER_FIGHT_INFO_REQUEST = 1016 -- 查询战斗数据请求
S_QUERY_PLAYER_FIGHT_INFO_RESPOND = 1017 -- 查询战斗数据返回


S_PLAYER_FIGHT_PREPARE_REQUEST = 1018 -- 准备玩家副本战斗数据
S_PLAYER_FIGHT_PREPARE_RESPOND = 1019 

S_PLAYER_FIGHT_CONFIRM_REQUEST = 1020 -- 副本战斗确认
S_PLAYER_FIGHT_CONFIRM_RESPOND = 1021 

S_NOTIFY_QUSET_EVENT_REQUEST = 1022 -- 通知任务事件
S_NOTIFY_QUSET_EVENT_RESPOND = 1023

S_QUERY_RECOMMEND_FIGHT_INFO_REQUEST = 1024 --查询指定阵容战斗数据请求
S_QUERY_RECOMMEND_FIGHT_INFO_RESPOND = 1025

S_PLAYER_CHANGE_NOTIFY = 1100   -- SPlayerChangeNotify
-- #define S_PLAYER_CHANGE_NOTIFY       3023    // aGameRespond

S_RUN_SCRIPT_REQUEST = 1900 -- 执行脚本请求 RunScriptRequest
S_RUN_SCRIPT_RESPOND = 1901 -- 执行脚本返回 aGameRespond

S_GET_SERVER_INFO_REQUEST = 1902
S_GET_SERVER_INFO_RESPOND = 1903
--------------------------------------------------------------------------------

NOTIFY_MAIL_NEW = 26    -- 新邮件通知   [id, type, title, status, [fromid, fromname]]
NOTIFY_CLOSE_FRIEND_ONLINE = 30 -- 亲密好友上线通知
NOTIFY_CONTACT_ADD = 31 -- 被加好友

--NOTIFY----------------
NOTIFY_GUILD_REQUEST = 19   -- 请求加入军团 [gid, [pid, name]]
NOTIFY_GUILD_JOIN = 20  -- 加入军团     [gid, [pid, pname]]
NOTIFY_GUILD_LEAVE = 21 -- 离开军团     [gid, [pid, pname], [oid, oname]]
NOTIFY_GUILD_NOTIFY = 22    -- 军团公告     [gid, notify]
NOTIFY_GUILD_LEADER = 23    -- 团长变更     [gid, [leaderid, leadername], [oid, oname]]
NOTIFY_GUILD_TITLE = 24 -- 职位变更     [gid, [pid, pname], [oid, oname], changetype, title]
NOTIFY_GUILD_AUDIT = 25 -- 同意加入变更 [[gid, gname], [oid, oname], type];
NOTIFY_GUILD_PRAY_PROGRESS_CHANGE = 27 -- 军团祈愿进度变化 
NOTIFY_GUILD_PRAY_LIST_CHANGE = 28 -- 军团祈愿求助列表变化 

NOTIFY_ITEM_COUNT  = 39
NOTIFY_DISPLAY_MESSAGE = 40 -- 显示消息 [type, message]

NOTIFY_GUILD_BOSS_OPEND  = 41
NOTIFY_GUILD_BOSS_SETTING  = 48 -- boss时间改变
NOTIFY_REWARD_CHANGE  = 49
NOTIFY_HERO_INFO =  50 -- 角色信息变化

NOTIFY_ADDICTED_CHANGE  = 51  -- [type, hour]  type:0 登录通知   1 每小时弹框 2 踢出弹框
NOTIFY_TALENT_INFO = 52 -- 天赋信息变通

NOTIFY_EQUIP = 53
NOTIFY_FIGHT = 54
NOTIFY_HERO_ITEM = 55
NOTIFY_QUEST = 56
NOTIFY_REWARDFLAG = 57
NOTIFY_QUEST_REWARD = 58
NOTIFY_FIRE = 59

-- NOTIFY_GUILD_5XING_CHANGE = 53   -- [[id,name,head,times], ...];
-- NOTIFY_GUILD_5XING_REWARD = 54   -- [[id,name, [[type,id,value],...]], ...]
-- NOTIFY_GUILD_5XING_PLAYER_TIMES_CHANGE = 55  -- [times]

NOTIFY_FIGHT_REWARD = 60 -- 显示在战斗结束的奖励  [type, rewards, ...]
	FIGHT_REWARD_TYPE_SCORE  = 1 -- 评分奖励
	FIGHT_REWARD_TYPE_BOUNTY = 2 -- 试炼活动
	FIGHT_REWARD_TYPE_TEAM_FIGHT_MONSTER_DIE = 3 -- 团队副本小怪死亡掉落
	FIGHT_REWARD_TYPE_TEAM_FIGHT_WIN = 4         -- 团队副本胜利奖励
	FIGHT_REWARD_TYPE_ARENA_PVP = 5  -- 竞技场pvp

NOTIFY_BUFF = 61

NOTIFY_GUILD_DONATE = 1106 --捐赠
NOTIFY_GUILD_BUY_MEMBER_COUNT = 1122; -- 军团有人购买军团成员数量
NOTIFY_GUILD_INVITE = 1126 -- 军团加入邀请
NOTIFY_GUILD_DONATE_HIGH = 1127 --军团二次捐献通知


NOTIFY_MANOR_HERO_LEAVE_TAVERN = 1129
NOTIFY_MANOR_HERO_BACK_TAVERN = 1130

NOTIFY_MANOR_LUCKY_EVENT = 1131
NOTIFY_MANOR_POPULAR_EVENT = 1132

NOTIFY_MANOR_LOG_CHANGE = 1133

NOTIFY_GUILD_MAP_EXPLORE_EVENT_CHANGE = 1134
NOTIFY_GUILD_EXPLORE_MAP_CHANGE = 1135
NOTIFY_GUILD_EXPLORE_EVENT_LOG_CHANGE = 1136
NOTIFY_GUILD_PRAY_LOG_CHANGE = 1137

NOTIFY_GUILD_WAR_FIGHT_RECORD = 1116; -- 军团战军团战报
NOTIFY_GUILD_WAR_STATUS       = 1117; -- 军团战军团战报
NOTIFY_GUILD_WAR_INSPIRE      = 1118; -- 军团战军团鼓舞值变化
NOTIFY_GUILD_WAR_MEMBER_JOIN  = 1119; -- 军团战报名成员变化
NOTIFY_GUILD_WAR_ORDER        = 1120; -- 军团战顺序改变
NOTIFY_GUILD_WAR_REPORT       = 1121; -- 军团战军团排名变化

NOTIFY_GUILD_QUEST_CHANGE     = 1128  -- 军团任务变化通知
NOTIFY_MANOR_OTHER_HELP_SPEEDUP = 1138
NOTIFY_SHARED_QUEST_CHANGE     = 1139  -- 共享任务变化通知

NOTIFY_BACKYARD_FAIRY_GOODFEEL = 1140 -- 妖精好感度的变化(每隔一小时通知一次)
NOTIFY_PLAYER_SHARED_QUEST_CHANGE = 1141 
NOTIFY_GUILD_ACTIVITY_END = 1142 
NOTIFY_GUILD_ITEM_CHANGE = 1143

NOTIFY_TEAM_BATTLE_INFO = 16200 -- team battle info change

-----------------------


--REQUEST---------------- 
C_ECHO = 0 --登入请求

C_LOGIN_REQUEST = 1 --登入请求
C_LOGIN_RESPOND = 2 --登入返回

C_LOGOUT_REQUEST = 3 --登出请求
C_LOGOUT_RESPOND = 4 --登出返回

C_QUERY_PLAYER_REQUEST = 5 --查询玩家信息请求
C_QUERY_PLAYER_RESPOND = 6 --查询玩家信息返回

C_CREATE_PLAYER_REQUEST = 7 --创建角色请求
C_CREATE_PLAYER_RESPOND = 8 --创建角色返回

C_QUERY_QUEST_REQUEST = 76 -- 查询任务
C_QUERY_QUEST_RESPOND = 77 

C_SET_QUEST_STATUS_REQUEST = 78 -- 完成、放弃任务
C_SET_QUEST_STATUS_RESPOND = 79 

C_PLAYER_DATA_CHANGE = 104 --状态更新
-- [sn, result, [type, ...], ...]
 
--ARENA COMMAND------
C_ARENA_JOIN_ARENA = 501
S_ARENA_JOIN_ARENA = 502

C_ARENA_GET_ENEMY_LIST = 503
S_ARENA_GET_ENEMY_LIST = 504

C_ARENA_UPDATE_FIGHT_RESULT = 505
S_ARENA_UPDATE_FIGHT_RESULT = 506


C_ARENA_RESET_ENEMY_LIST_REQUEST = 507
C_ARENA_RESET_ENEMY_LIST_RESPOND = 508

C_ARENA_INSPIRE_PLAYER_REQUEST = 509
C_ARENA_INSPIRE_PLAYER_RESPOND = 510

C_ARENA_DRAW_REWARD_REQUEST = 511
C_ARENA_DRAW_REWARD_RESPOND = 512

C_ARENA_QUERY_PLAYER_INFO_REQUEST = 513
C_ARENA_QUERY_PLAYER_INFO_RESPOND = 514

C_ARENA_FIGHT_PREPARE_REQUEST = 515
C_ARENA_FIGHT_PREPARE_RESPOND = 516

C_PILLAGE_ARENA_FIGHT_PERPARE_REQUEST = 517
C_PILLAGE_ARENA_FIGHT_PERPARE_RESPOND = 518

C_PILLAGE_ARENA_FIGHT_CHECK_REQUEST = 519
C_PILLAGE_ARENA_FIGHT_CHECK_RESPOND = 520

C_PILLAGE_ARENA_QUERY_RANK_LIST_REQUEST = 521
C_PILLAGE_ARENA_QUERY_RANK_LIST_RESPOND = 522

C_PILLAGE_ARENA_QUERY_LAST_PERIOD_CHAMPION_REQUEST = 523
C_PILLAGE_ARENA_QUERY_LAST_PERIOD_CHANPION_RESPOND = 524

C_PILLAGE_ARENA_QUERY_FORMATION_REQUEST = 525
C_PILLAGE_ARENA_QUERY_FORMATION_RESPOND = 526

C_PILLAGE_ARENA_CHANGE_FORMATION_REQUEST = 527
C_PILLAGE_ARENA_CHANGE_FORMATION_RESPOND = 528

C_PILLAGE_ARENA_QUERY_PLAYER_INFO_REQUEST = 529
C_PILLAGE_ARENA_QUERY_PLAYER_INFO_RESPOND = 530

C_PILLAGE_ARENA_QUERY_PLAYER_LOG_REQUEST = 531
C_PILLAGE_ARENA_QUERY_PLAYER_LOG_RESPOND = 532

NOTIFY_ARENA_LOG_CHANGE = 550

S_GET_RANKLIST_REQUEST = 551	-- 获取排名列表
S_GET_RANKLIST_RESPOND = 552

C_PILLAGE_MATCH_REQUEST = 553
C_PILLAGE_MATCH_RESPOND = 554

C_PILLAGE_MATCH_CANCEL_REQUEST = 555
C_PILLAGE_MATCH_CANCEL_RESPOND = 556

NOTIFY_MATCH_SUCCESS = 557

C_PILLAGE_APPLY_FIGHT_REQUET = 558
C_PILLAGE_APPLY_FIGHT_RESPOND = 559

--------rank arena 排名竞技场-------
C_ARENA_QUERY_REQUEST = 561 -- 竞技场查询请求
C_ARENA_QUERY_RESPOND = 562 -- 竞技场查询返回

C_ARENA_ATTACK_REQUEST = 563 -- 竞技场攻击请求
C_ARENA_ATTACK_RESPOND = 564 -- 竞技场攻击返回

C_ARENA_FIGHT_CHECK_REQUEST = 565 
C_ARENA_FIGHT_CHECK_RESPOND = 566

C_ARENA_JOIN_REQUEST = 567 -- 加入竞技场请求
C_ARENA_JOIN_RESPOND = 568 -- 加入竞技场返回

C_ARENA_REWARD_REQUEST = 569 -- 领取竞技场奖励请求
C_ARENA_REWARD_RESPOND = 570 -- 领取竞技场奖励放回

C_ARENA_RESET_CD_REQUEST = 571 -- 清除竞技场cd请求
C_ARENA_RESET_CD_RESPOND = 572 -- 清除竞技场cd返回

C_ARENA_ADD_FIGHTCOUNT_REQUEST = 573 -- 加次数
C_ARENA_ADD_FIGHTCOUNT_RESPOND = 574 -- 加次数

C_ARENA_QUERY_TOP_REQUEST = 575
C_ARENA_QUERY_TOP_RESPOND = 576

C_ARENA_REFRESH_ENEMY_LIST_REQUEST = 577
C_ARENA_REFRESH_ENEMY_LIST_RESPOND = 578

C_ARENA_CHANGE_FORMATION_REQUEST = 579
C_ARENA_CHANGE_FORMATION_RESPOND = 580

NOTIFY_ARENA_ATTACK = 581

NOTIFY_ARENA_AI_ENTER = 582

NOTIFY_FIGHT_RESULT = 583

S_ARENA_ADD_WEALTH_REQUEST = 589
S_ARENA_ADD_WEALTH_RESPOND = 590

C_PILLAGE_ADD_WEALTH_REQUEST = 591
C_PILLAGE_ADD_WEALTH_RESPOND = 592

C_PILLAGE_CLOSE_PVE_FIGHT_REQUEST = 593
C_PILLAGE_CLOSE_PVE_FIGHT_RESPOND = 594

C_ARENA_ATTACK_SGK_REQUEST = 595 
C_ARENA_ATTACK_SGK_RESPOND = 596 

C_ARENA_QUERY_LOG_REQUEST = 597
C_ARENA_QUERY_LOG_RESPOND = 598

NOTIFY_RANK_ARENA_LOG_CHANGE = 599

C_ARENA_QUERY_FORMATION_REQUEST = 533 
C_ARENA_QUERY_FORMATION_RESPOND = 534 
--------------------------------------

--------------------

--SHOP COMMAND-----
--SHOP
C_GET_SPECIAL_SHOP =15001
S_GET_SPECIAL_SHOP =15002

C_GET_VALID_TIME =15003
S_GET_VALID_TIME =15004

C_BUY =15005
S_BUY =15006

C_BUY_FOR_GUILD_SHOP =15007
S_BUY_FOR_GUILD_SHOP =15008

C_BUY_FOR_HERO_ITEM =15009
S_BUY_FOR_HERO_ITEM =15010

C_GET_GIFT_BAG =15011
S_GET_GIFT_BAG =15012

C_GET_OPEN_GIFT_BAG_HISTORY = 15013
S_GET_OPEN_GIFT_BAG_HISTORY = 15014

C_OPEN_GIFT_BAG =15015
S_OPEN_GIFT_BAG =15016

C_FRESH_SPECIAL_SHOP =15017
S_FRESH_SPECIAL_SHOP =15018

-- C_BUY_ITEM_MAP = 15019
-- S_BUY_ITEM_MAP = 15020

-- SWEEPSTAKE
C_SWEEPSTAKE_REQUEST = 15079 --抽奖
S_SWEEPSTAKE_RESPOND = 15080

C_QUERY_SWEEPSTAKE_CONFIG_REQUEST = 15081 --抽奖活动配置
S_QUERY_SWEEPSTAKE_CONFIG_RESPOND = 15082

C_QUERY_SWEEPSTAKE_PLAYER_INFO_REQUEST = 15083 --抽奖个人信息
S_QUERY_SWEEPSTAKE_PLAYER_INFO_RESPOND = 15084

C_QUERY_SWEEPSTAKE_RANKLIST_REQUEST = 15085
S_QUERY_SWEEPSTAKE_RANKLIST_RESPOND = 15086

C_QUERY_SWEEPSTAKE_SCORE_REQUEST = 15087
S_QUERY_SWEEPSTAKE_SCORE_RESPOND = 15088

C_QUERY_SWEEPSTAKE_FINAL_REWARD_CONFIG_REQUEST = 15089
S_QUERY_SWEEPSTAKE_FINAL_REWARD_CONFIG_RESPOND = 15090

C_QUERY_SWEEPSTAKE_SCORE_REWARD_CONFIG_REQUEST = 15091
S_QUERY_SWEEPSTAKE_SCORE_REWARD_CONFIG_RESPOND = 15092

C_ACHIEVE_SWEEPSTAKE_SCORE_REWARD_REQUEST = 15093
S_ACHIEVE_SWEEPSTAKE_SCORE_REWARD_RESPOND = 15094

C_SWEEPSTAKE_CHANGE_POOL_REQUEST = 15095 --换奖池
S_SWEEPSTAKE_CHANGE_POOL_RESPOND = 15096

C_SWEEPSTAKE_CHANGE_POOL_AND_SWEEPSTAKE_REQUEST = 15097 -- 换奖池并抽将
S_SWEEPSTAKE_CHANGE_POOL_AND_SWEEPSTAKE_RESPOND = 15098

------------------------------------------------
RET_TRADE_NOT_EXIST = 2  -- 订单不存在
RET_TRADE_OUTOFDATE = 3  -- 订单过期
RET_TRADE_EXCHAGE_FAIL = 5 -- 交易失败

C_TRADE_QUERY_PLAYER_ORDERS_REQUEST = 15101
C_TRADE_QUERY_PLAYER_ORDERS_RESPOND = 15102

C_TRADE_SELL_REQUEST = 15103
C_TRADE_SELL_RESPOND = 15104

C_TRADE_TAKE_BACK_REQUEST = 15105
C_TRADE_TAKE_BACK_RESPOND = 15106

C_TRADE_BUY_REQUEST = 15107
C_TRADE_BUY_RESPOND = 15108

C_TRADE_QUERY_ORDERS_RANK_REQUEST = 15109
C_TRADE_QUERY_ORDERS_RANK_RESPOND = 15110

C_TRADE_QUERY_COMMODITY_CONFIG_REQUEST = 15111
C_TRADE_QUERY_COMMODITY_CONFIG_RESPOND = 15112

C_TRADE_QUERY_TRADEORDERS_REQUEST = 15113
C_TRADE_QUERY_TRADEORDERS_RESPOND = 15114

C_TRADE_SET_COMMODITY_CONCERN_REQUEST = 15115
C_TRADE_SET_COMMODITY_CONCERN_RESPOND = 15116

C_TRADE_QUERY_COMMODITY_CONCERN_REQUEST = 15117
C_TRADE_QUERY_COMMODITY_CONCERN_RESPOND = 15118


-------------------
------------------------
--GUILD COMMAND----
C_GUILD_MIN = 3000

C_GUILD_QUERY_REQUEST = 3000 --查询军团请求
--[sn, guildid]
C_GUILD_QUERY_RESPOND = 3001 --查询军团返回
--[sn,result,guildid,name,grade,rank,people,qq,exp,功勋,公告]

C_GUILD_CREATE_REQUEST = 3002 --创建军团请求
--[sn, name]
C_GUILD_CREATE_RESPOND = 3003 --创建军团返回
--[sn, C = ommand.RET_SUCCESS = , guild.id]


C_GUILD_JOIN_REQUEST = 3004 --加入军团请求
-- [sn, gid]
C_GUILD_JOIN_RESPOND = 3005 --加入军团返回
-- [sn, result, "success"/"failed"]

C_GUILD_LEAVE_REQUEST = 3006 --脱离军团请求
--[sn]
C_GUILD_LEAVE_RESPOND = 3007 --脱离军团返回
--[sn, result, "success"/"failed"]

C_GUILD_QUERY_GUILD_LIST_REQUEST = 3008 --查询军团列表请求
--[sn]
C_GUILD_QUERY_GUILD_LIST_RESPOND = 3009 --查询军团列表返回
--[sn, ret, [guild.id, guild.name, guild.leader.id, guild.leader.name, guild.mcount], ...]

C_GUILD_QUERY_MEMBERS_REQUEST = 3010 --查询军团成员列表请求
--[sn]
C_GUILD_QUERY_MEMBERS_RESPOND = 3011 --查询军团成员列表返回
--[sn, ret, [m.id, m.name, m.level], ...]

C_GUILD_QUERY_APPLY_REQUEST = 3016 --查询军团申请列表请求
--[sn]
C_GUILD_QUERY_APPLY_RESPOND = 3017 --查询军团申请列表返回
--[sn, ret, [playerid, name, level], ...];

C_GUILD_AUDIT_REQUEST = 3018 --军团审核请求
--[sn, playerid, type] type:1 同意， 2 不同意
C_GUILD_AUDIT_RESPOND = 3019 --军团审核返回
--[sn, result, "success"/"failed"]

C_GUILD_SETTING_REQUEST = 3020 --军团设置请求
--[sn, notice]
C_GUILD_SETTING_RESPOND = 3021 --军团设置返回
--[sn, result, "success"/"failed"]

C_GUILD_TRANSFER_REQUEST = 3022 --军团转让请求 【转让和职位设置可以合并到一起】
--[sn,id]
C_GUILD_TRANSFER_RESPOND = 3023 --军团转让返回

C_GUILD_DISSOLVE_REQUEST = 3026 --解散军团请求
--[sn]
C_GUILD_DISSOLVE_RESPOND = 3027 --解散军团返回
--[sn,result,guildname]

C_GUILD_QUEYR_BY_PLAYER_REQUEST = 3028 -- 查询玩家所属军团请求
--[sn, playerid]
C_GUILD_QUEYR_BY_PLAYER_RESPOND = 3029 -- 查询玩家所属军团返回
--[sn,result,[pid,title],[gid,...]] guildid = 0 表示没有军团

C_GUILD_SET_TITLE_REQUEST = 3030 -- 设置头衔请求
C_GUILD_SET_TITLE_RESPOND = 3031 -- 设置头衔返回
C_GUILD_INVITE_REQUEST = 3032 -- 邀请加入请求
C_GUILD_INVITE_RESPOND = 3033 -- 邀请加入返回

C_GUILD_QUERY_PLAYER_REQUEST = 3034 -- 查询军团玩家信息请求
-- [sn, playerid]
C_GUILD_QUERY_PLAYER_RESPOND = 3035 -- 查询军团玩家信息返回
-- [sn, pid, gid, [title, ...]]

C_GUILD_SET_LEADER_REQUEST = 3036 -- 设置军团长请求
-- [sn, playerid]
C_GUILD_SET_LEADER_RESPOND = 3037 -- 设置军团长返回
-- [sn, result, playerid]

C_GUILD_QUERY_BY_TITLE_REQUEST = 3038 -- 通过职位查询角色请求
-- [sn, title]

C_GUILD_QUERY_BY_TITLE_RESPOND = 3039 -- 通过职位查询角色返回
-- [sn, result, [playerid, name, level], ...]

C_GUILD_KICK_REQUEST = 3040 -- 踢人请求
-- [sn, playerid]
C_GUILD_KICK_RESPOND = 3041 -- 踢人返回

-- [sn, result, playerid]
C_GUILD_CLEAN_ALL_REQUEST = 3042 -- 清除所有申请请求
-- [sn]
C_GUILD_CLEAN_ALL_RESPOND = 3043 -- 清除所有申请请求
-- [sn, result]

C_GUILD_BOSS_SETTING_REQUEST = 3044 -- 设置boss时间请求
-- [sn, boss]

C_GUILD_BOSS_SETTING_RESPOND = 3045 -- 设置boss时间返回
-- [sn, result, boss]

C_QUERY_GUILD_EXP_LOG_REQUEST = 3046 --
-- [sn]

C_QUERY_GUILD_EXP_LOG_RESPOND = 3047
-- [sn, result, [time, [pid,name] exp], ...]


C_GUILD_5XING_QUERY_REQUEST = 3048 -- 查询玩家参加信息
C_GUILD_5XING_QUERY_RESPOND = 3049

C_GUILD_5XING_JOIN_REQUEST = 3050  -- 加入
C_GUILD_5XING_JOIN_RESPOND = 3051

C_GUILD_5XING_BUY_REQUEST =  3052 -- 购买
C_GUILD_5XING_BUY_RESPOND =  3053

C_GUILD_5XING_QUERY_SLOT_REQUEST = 3054 -- 查询当前阵型
C_GUILD_5XING_QUERY_SLOT_RESPOND = 3055

C_GUILD_BUY_MEMBER_COUNT_REQUEST = 3142 -- 军团成员数量购买请求
C_GUILD_BUY_MEMBER_COUNT_RESPOND = 3143 -- 购买返回

C_GUILD_SEARCH_NAME_REQUEST = 3144 --军团按名字模糊查询
C_GUILD_SEARCH_NAME_RESPOND = 3145

C_GUILD_ACCEPT_INVITE_REQUEST = 3146 --接受邀请
C_GUILD_ACCEPT_INVITE_RESPOND = 3147

S_GUILD_QUERY_BY_GUILDID_REQUEST = 3088
S_GUILD_QUERY_BY_GUILDID_RESPOND = 3089
-- [sn,result,rewardId]]
S_GUILD_QUERY_BY_PLAYER_REQUEST = 3090 -- 查询玩家所属军团请求
-- GuildQueryByPlayerRequest
S_GUILD_QUERY_BY_PLAYER_RESPOND = 3091 -- 查询玩家所属军团返回
-- GuildQueryByPlayerRespond

S_GUILD_ADD_EXP_REQUEST = 3092  -- 增加军团经验请求
-- PGuildAddExpRequest
S_GUILD_ADD_EXP_RESPOND = 3093  -- 增加军团经验返回
-- aGameRespond;

C_GUILD_DONATE_REQUEST = 3094 -- 军团捐献请求
-- [sn, type]
C_GUILD_DONATE_RESPOND = 3095 -- 军团捐献返回

C_GUILD_QUERY_DONATE_REQUEST = 3096 -- 查询军团捐献请求
-- [sn, count]
C_GUILD_QUERY_DONATE_RESPOND = 3097 -- 查询军团捐献返回
-- [sn, result, value, [type, time]]

C_GUILD_PRAY_QUERY_PLAYER_INFO_REQUEST =3098	
C_GUILD_PRAY_QUERY_PLAYER_INFO_RESPOND =3099	

C_GUILD_PRAY_RESET_REQUEST = 3100
C_GUILD_PRAY_RESET_RESPOND = 3101

C_GUILD_PRAY_UPDATE_PROGRESS_REQUEST = 3102
C_GUILD_PRAY_UPDATE_PROGRESS_RESPOND = 3103

C_GUILD_PRAY_DRAW_REWARD_REQUEST = 3104
C_GUILD_PRAY_DRAW_REWARD_RESPOND = 3105

C_GUILD_PRAY_SEEK_HELP_REQUEST = 3106
C_GUILD_PRAY_SEEK_HELP_RESPOND = 3107

C_GUILD_PRAY_QUERY_LIST_REQUEST = 3108
C_GUILD_PRAY_QUERY_LIST_RESPOND = 3109

C_GUILD_PRAY_HELP_OTHERS_REQUEST = 3110
C_GUILD_PRAY_HELP_OTHERS_RESPOND = 3111

C_GUILD_EXPLORE_QUERY_MAP_INFO_REQUEST = 3112
C_GUILD_EXPLORE_QUERY_MAP_INFO_RESPOND = 3113

C_GUILD_EXPLORE_QUERY_PLAYER_TEAM_INFO_REQUEST = 3114
C_GUILD_EXPLORE_QUERY_PLAYER_TEAM_INFO_RESPOND = 3115

C_GUILD_EXPLORE_ATTEND_REQUEST = 3116
C_GUILD_EXPLORE_ATTEND_RESPOND = 3117

C_GUILD_EXPLORE_STOP_REQUEST = 3118
C_GUILD_EXPLORE_STOP_RESPOND = 3119

C_GUILD_EXPLORE_RESET_REQUEST = 3120
C_GUILD_EXPLORE_RESET_RESPOND = 3121

C_GUILD_EXPLORE_DRAW_REWARD_REQUEST = 3122
C_GUILD_EXPLORE_DRAW_REWARD_RESPOND = 3123

C_GUILD_DRAW_DONATE_REWARD_REQUEST = 3124
C_GUILD_DRAW_DONATE_REWARD_RESPOND = 3125

C_GUILD_SEARCH_ID_REQUEST = 3126
C_GUILD_SEARCH_ID_RESPOND = 3127

C_GUILD_AUTO_CONFIRM_REQUEST = 3128
C_GUILD_AUTO_CONFIRM_RESPOND = 3129

C_GUILD_AUTO_JOIN_REQUEST = 3130
C_GUILD_AUTO_JOIN_RESPOND = 3131

C_GUILD_QUERY_BUILDING_INFO_REQUEST = 3132
C_GUILD_QUERY_BUILDING_INFO_RESPOND = 3133

C_GUILD_LEVEL_UP_BUILDING_REQUEST = 3134
C_GUILD_LEVEL_UP_BUILDING_RESPOND = 3135

S_GUILD_QUERY_BUILDING_LEVEL_REQUEST = 3136
S_GUILD_QUERY_BUILDING_LEVEL_RESPOND = 3137

C_GUILD_QUERY_PLAYER_AUTO_JOIN_REQUEST = 3138
C_GUILD_QUERY_PLAYER_AUTO_JOIN_RESPOND = 3139

S_GUILD_QUERY_REQUEST = 3140
S_GUILD_QUERY_RESPOND = 3141 

S_GUILD_APPLY_NOTIFY = 3201

S_GUILD_DONATE_NOTIFY = 3204

S_SEEK_PRAY_HELP_NOTIFY = 3206

S_HELP_PRAY_NOTIFY = 3208

S_GUILD_DISPEAR_NOTIFY = 3210

C_GUILD_EXPLORE_QUERY_EVENT_REQUEST = 3212
C_GUILD_EXPLORE_QUERY_EVENT_RESPOND = 3213

C_GUILD_EXPLORE_FINISH_EVENT_REQUEST = 3214
C_GUILD_EXPLORE_FINISH_EVENT_RESPOND = 3215

C_GUILD_EXPLORE_QUERY_EVENT_LOG_REQUEST = 3216
C_GUILD_EXPLORE_QUERY_EVENT_LOG_RESPOND = 3217

C_GUILD_QUERY_PRAY_LOG_REQUEST = 3218
C_GUILD_QUERY_PRAY_LOG_RESPOND = 3219

C_GUILD_WAR_ENTER_REQUEST              = 3320  -- 进入军团战活动请求
C_GUILD_WAR_ENTER_RESPOND              = 3321  -- 

C_GUILD_WAR_LEAVE_REQUEST              = 3322  -- 离开军团战活动请求
C_GUILD_WAR_LEAVE_RESPOND              = 3323  -- 

C_GUILD_WAR_JOIN_REQUEST               = 3324  -- 军团报名参加活动
C_GUILD_WAR_JOIN_RESPOND               = 3325  -- 

C_GUILD_WAR_INSPIRE_REQUEST            = 3326  -- 军团战鼓舞
C_GUILD_WAR_INSPIRE_RESPOND            = 3327

C_GUILD_WAR_ENTER_SUB_ROOM_REQUEST     = 3328 --军团进入子房间
C_GUILD_WAR_ENTER_SUB_ROOM_RESPOND    = 3329 --

C_GUILD_WAR_QUERY_REPORT_REQUEST            = 3330 --军团查询榜单信息
C_GUILD_WAR_QUERY_REPORT_RESPOND            = 3331

C_GUILD_WAR_SET_ORDER_REQUEST = 3332   -- 军团设置主将顺序
C_GUILD_WAR_SET_ORDER_RESPOND = 3333

C_GUILD_WAR_QUERY_HISTORY_REPORT_REQUEST = 3334  -- 军团查询历史榜单数据
C_GUILD_WAR_QUERY_HISTORY_REPORT_RESPOND = 3335

C_GUILD_WAR_LEAVE_SUB_ROOM_REQUEST     = 3336 --军团离开子房间
C_GUILD_WAR_LEAVE_SUB_ROOM_RESPOND     = 3337 --

C_GUILD_WAR_QUERY_HISTORY_FIGHT_RECORD_REQUEST = 3338  -- 军团查询历史战斗数据
C_GUILD_WAR_QUERY_HISTORY_FIGHT_RECORD_RESPOND = 3339

C_GUILD_WAR_QUERY_ORDER_REQUEST = 3340  -- 军团查询任命请求
C_GUILD_WAR_QUERY_ORDER_RESPOND = 3341  -- 军团查询任命返回

S_GUILD_EXPLORE_NOTIFY = 3342	-- 军团探险行为

S_NOTIFY_AI_LOGIN_GUILD = 3343
S_NOTIFY_AI_LOGOUT_GUILD = 3344

C_GUILD_BOSS_QUERY_OPEN_CONFIG_REQUEST = 3211
C_GUILD_BOSS_QUERY_OPEN_CONFIG_RESPOND = 3212

C_GUILD_BOSS_QUERY_INFO_REQUEST = 3345
C_GUILD_BOSS_QUERY_INFO_RESPOND = 3346

C_GUILD_BOSS_OPEN_REQUEST = 3347
C_GUILD_BOSS_OPEN_RESPOND = 3348

C_GUILD_BOSS_QUERY_RANKLIST_REQUEST = 3349
C_GUILD_BOSS_QUERY_RANKLIST_RESPOND = 3350

C_GUILD_BOSS_FIGHT_PREPARE_REQUEST = 3351
C_GUILD_BOSS_FIGHT_PREPARE_RESPOND = 3352

C_GUILD_BOSS_FIGHT_CHECK_REQUEST = 3353
C_GUILD_BOSS_FIGHT_CHECK_RESPOND = 3354

C_GUILD_BOSS_CURINFO_REQUEST = 3355 -- 查询boss当前信息
C_GUILD_BOSS_CURINFO_RESPOND = 3356

C_GUILD_QUEST_QUERY_INFO_REQUEST = 3357
C_GUILD_QUEST_QUERY_INFO_RESPOND = 3358

C_GUILD_QUEST_ACCEPT_REQUEST = 3359
C_GUILD_QUEST_ACCEPT_RESPOND = 3360

C_GUILD_QUEST_CANCEL_REQUEST = 3361
C_GUILD_QUEST_CANCEL_RESPOND = 3362

C_GUILD_QUEST_SUBMIT_REQUEST = 3363
C_GUILD_QUEST_SUBMIT_RESPOND = 3364

C_GUILD_EXPLORE_FIGHT_PREPARE_REQUEST = 3365
C_GUILD_EXPLORE_FIGHT_PREPARE_RESPOND = 3366

C_GUILD_EXPLORE_FIGHT_CHECK_REQUEST = 3367
C_GUILD_EXPLORE_FIGHT_CHECK_RESPOND = 3368

C_SHARED_QUEST_QUERY_INFO_REQUEST = 3369
C_SHARED_QUEST_QUERY_INFO_RESPOND = 3370

C_SHARED_QUEST_ACCEPT_REQUEST = 3371
C_SHARED_QUEST_ACCEPT_RESPOND = 3372

C_SHARED_QUEST_CANCEL_REQUEST = 3373
C_SHARED_QUEST_CANCEL_RESPOND = 3374

C_SHARED_QUEST_SUBMIT_REQUEST = 3375
C_SHARED_QUEST_SUBMIT_RESPOND = 3376

C_SHARED_QUEST_PLAYER_QUEST_QUERY_REQUEST = 3377
C_SHARED_QUEST_PLAYER_QUEST_QUERY_RESPOND = 3378

S_NOTIFY_AI_LEADER_WORK = 3379

C_GUILD_QUEST_COST_ITEM_TO_UPDATE_RECORD_REQUEST = 3381
C_GUILD_QUEST_COST_ITEM_TO_UPDATE_RECORD_RESPOND = 3382

C_GUILD_QUEST_ACHIEVE_STEP_REWARD_REQUEST = 3383
C_GUILD_QUEST_ACHIEVE_STEP_REWARD_RESPOND = 3384

C_NPC_QUERY_INFO_REQUEST = 3385
C_NPC_QUERY_INFO_RESPOND = 3386

C_NPC_INTERACT_REQUEST = 3387
C_NPC_INTERACT_RESPOND = 3388

C_NPC_INVEST_REQUEST = 3389
C_NPC_INVEST_RESPOND = 3390

C_GUILD_ITEM_QUERY_REQUEST = 3391
C_GUILD_ITEM_QUERY_RESPOND = 3392

C_GUILD_ITEM_ADD_REQUEST = 3393
C_GUILD_ITEM_ADD_RESPOND = 3394

C_GUILD_MAX = 3999
------------------
--------------------


-- 庄园 --
C_MANOR_MANUFACTURE_QUERY_PRODUCT_LINE_REQUEST = 11001 --查询生产请求
-- [sn]
C_MANOR_MANUFACTURE_QUERY_PRODUCT_LINE_RESPOND = 11002 --查询生产返回
-- [sn, [[line,gid,speed,gather_time], ...]]

C_MANOR_MANUFACTURE_QUERY_PRODUCT_REQUEST = 11003 --查询生产列表请求
-- [sn]
C_MANOR_MANUFACTURE_QUERY_PRODUCT_RESPOND = 11004 --查询生产列表返回
-- [sn, [[gid,time,[[type,id,value],...], ...]]]

C_MANOR_MANUFACTURE_GATHER_REQUEST = 11005 -- 收获请求
-- [sn, line]
C_MANOR_MANUFACTURE_GATHER_RESPOND = 11006 -- 收获返回
-- [sn, [line,gid]]

C_MANOR_MANUFACTURE_PRODUCT_REQUEST = 11007 -- 开始生产请求
-- [sn, line]
C_MANOR_MANUFACTURE_PRODUCT_RESPOND = 11008 -- 开始生产返回
-- [sn, [line,gid,speed,gather_time]]

C_MANOR_MANUFACTURE_SPEEDUP_REQUEST = 11009 -- 加速生产请求
-- [sn, line, speed]
C_MANOR_MANUFACTURE_SPEEDUP_RESPOND = 11010 -- 加速生产返回
-- [sn, [line,gid,speed,gather_time]]

C_MANOR_MANUFACTURE_EMPLOY_REQUEST = 11011 -- 雇佣工人请求
-- [sn , line, id, pos]
C_MANOR_MANUFACTURE_EMPLOY_RESPOND = 11012 -- 雇佣工人返回
-- [sn, ret]

C_MANOR_MANUFACTURE_LINE_LEVELUP_REQUEST = 11013 -- 升级生产线请求
-- [sn, line, level]
C_MANOR_MANUFACTURE_LINE_LEVELUP_RESPOND = 11014 -- 升级生产线返回
-- [sn, ret]
C_MANOR_MANUFACTURE_EVALUATE_WORKMAN_REQUEST = 11015 -- 评定工人属性值请求
-- [sn, workman_id, property_id, property_value]
C_MANOR_MANUFACTURE_EVALUATE_WORKMAN_RESPOND = 11016 -- 评定工人属性值返回
-- [sn, ret]
C_MANOR_MANUFACTURE_QUERY_WORKMAN_INFO_REQUEST = 11017 -- 获取工人属性信息请求 
-- [sn, workman_id]
C_MANOR_MANUFACTURE_QUERY_WORKMAN_INFO_RESPOND = 11018 -- 获取工人属性信息返回
-- [sn, ret, power, power_upper_limit, speed, power_next_change_time, [[property_id, property_vlaue], ...]]
C_MANOR_MANUFACTURE_INCREASE_POWER_REQUEST = 11019    -- 提高工人活力请求
-- [sn, workman_id, add_value]
C_MANOR_MANUFACTURE_INCREASE_POWER_RESPOND = 11020    -- 提高工人活力返回
-- [sn, ret]
C_MANOR_MANUFACTURE_INCREASE_LINE_STORAGE_REQUEST = 11021    -- 提高临时存储量上限请求
-- [sn, line, add_value]
C_MANOR_MANUFACTURE_INCREASE_LINE_STORAGE_RESPOND = 11022    -- 提高临时存储量上限返回
-- [sn, ret]
C_MANOR_MANUFACTURE_COPY_REQUEST = 11023	-- 庄园副本请求
C_MANOR_MANUFACTURE_COPY_RESPOND = 11024	-- 庄园副本返回

C_MANOR_MANUFACTURE_COPY_CHECK_REQUEST = 11025	-- 副本检查请求
C_MANOR_MANUFACTURE_COPY_CHECK_RESPOND = 11026	-- 副本检查返回

C_MANOR_QUERY_HERO_STATUS_REQUEST = 11027
C_MANOR_QUERY_HERO_STATUS_RESPOND = 11028

C_MANOR_TASK_REQUEST = 11029			-- 任务请求
C_MANOR_TASK_RESPOND = 11030			-- 任务请求返回
C_MANOR_GET_TASK_REQUEST = 11031		-- 领取任务
C_MANOR_GET_TASK_RESPOND = 11032		-- 领取任务返回
C_MANOR_REFRESH_TASK_REQUEST = 11033            -- 任务刷新
C_MANOR_REFRESH_TASK_RESPOND = 11034		-- 任务刷新返回
C_MANOR_TASK_DONE_REQUEST = 11035		-- 任务完成
C_MANOR_TASK_DONE_RESPOND = 11036		-- 任务完成返回
C_MANOR_TERM_TASK_REQUEST = 11037		-- 终止任务
C_MANOR_TERM_TASK_RESPOND = 11038		-- 终止任务返回
C_MANOR_EARLY_DONE_REQUEST = 11039		-- 提前完成任务
C_MANOR_EARLY_DONE_RESPOND = 11040		-- 提前完成任务返回


C_MANOR_CITY_CONTRUCT_ACCEPT_QUEST_REQUEST = 11041
C_MANOR_CITY_CONTRUCT_ACCEPT_QUEST_RESPOND = 11042

C_MANOR_CITY_CONTRUCT_CANCEL_QUEST_REQUEST = 11043
C_MANOR_CITY_CONTRUCT_CANCEL_QUEST_RESPOND = 11044

C_MANOR_CITY_CONTRUCT_SUBMIT_QUEST_REQUEST = 11045
C_MANOR_CITY_CONTRUCT_SUBMIT_QUEST_RESPOND = 11046

C_MANOR_CITY_CONTRUCT_INTERACT_REQUEST = 11047
C_MANOR_CITY_CONTRUCT_INTERACT_RESPOND = 11048

C_MANOR_CITY_CONTRUCT_QUERY_REQUEST = 11049
C_MANOR_CITY_CONTRUCT_QUERY_RESPOND = 11050

C_MANOR_STAR_REWARD_INFO_REQUEST = 11051	-- 查询玩家星星数和星星宝箱领取状态
C_MANOR_STAR_REWARD_INFO_RESPOND = 11052
C_MANOR_STAR_REWARD_REQUEST = 11053		-- 获得星星宝箱奖励
C_MANOR_STAR_REWARD_RESPOND = 11054
C_MANOR_REFRESH_ALLTASK_REQUEST = 11057		-- 刷新任务
C_MANOR_REFRESH_ALLTASK_RESPOND = 11058


C_MANOR_MANUFACTURE_INCREASE_LINE_ORDER_LIMIT_REQUEST = 11071    -- 提高订单上限请求
C_MANOR_MANUFACTURE_INCREASE_LINE_ORDER_LIMIT_RESPOND = 11072

C_MANOR_QUERY_LOG_REQUEST = 11073
C_MANOR_QUERY_LOG_RESPOND = 11074

C_MANOR_MANUFACTURE_TRIGGER_EVENT_REQUEST = 11075
C_MANOR_MANUFACTURE_TRIGGER_EVENT_RESPOND = 11076

C_MANOR_MANUFACTURE_WORKMAN_TITLE_CHANGE_REQUEST = 11077    --客户端通知服务器生产称号发生改变
C_MANOR_MANUFACTURE_WORKMAN_TITLE_CHANGE_RESPOND = 11078

C_MANOR_MANUFACTURE_UNLOCK_LINE_REQUEST = 11079 --解锁生产线
C_MANOR_MANUFACTURE_UNLOCK_LINE_RESPOND = 11080

C_MANOR_MANUFACTURE_QUERY_LINE_OPEN_STATUS_REQUEST = 11081 --查询生产线解锁状态
C_MANOR_MANUFACTURE_QUERY_LINE_OPEN_STATUS_RESPOND = 11082

C_MANOR_MANUFACTURE_HELP_OTHER_SPEEDUP_REQUEST = 11083
C_MANOR_MANUFACTURE_HELP_OTHER_SPEEDUP_RESPOND = 11084

C_MANOR_QUERY_TODAY_TASK_REQUEST = 11085
C_MANOR_QUERY_TODAY_TASK_RESPOND = 11086

C_MANOR_RANDOM_NPC_REQUEST = 11087
C_MANOR_RANDOM_NPC_RESPOND = 11088

C_MANOR_RANDOM_QUEST_REQUEST = 11089
C_MANOR_RANDOM_QUEST_RESPOND = 11090

C_MANOR_MANUFACTURE_SPEEDUP_BY_WORKMAN_REQUEST = 11091
C_MANOR_MANUFACTURE_SPEEDUP_BY_WORKMAN_RESPOND = 11092

C_MANOR_MANUFACTURE_CANCEL_ORDER_REQUEST = 11093
C_MANOR_MANUFACTURE_CANCEL_ORDER_RESPOND = 11094

C_GET_NPC_INFO_REQUEST = 11095
C_GET_NPC_INFO_RESPOND = 11096

C_GET_NPC_FIGHT_RESULT = 11097
C_GET_NPC_FIGHT_RESPOND = 11098

C_CHALLENGE_NPC_REQUEST = 11099
C_CHALLENGE_NPC_RESPOND = 11100

C_GET_RANKLIST_REQUEST = 11101
C_GET_RANKLIST_RESPOND = 11102

NOTIFY_FIGHT_RECORD = 11103
NOTIFY_RANK_LIST = 11104
NOTIFY_GUILD_BOSS = 11105

C_MANOR_RESET_LINE_PRODUCE_RATE_FIGHT_PREPARE_REQUEST = 11107
C_MANOR_RESET_LINE_PRODUCE_RATE_FIGHT_PREPARE_RESPOND = 11108

C_MANOR_RESET_LINE_PRODUCE_RATE_FIGHT_CHECK_REQUEST = 11109
C_MANOR_RESET_LINE_PRODUCE_RATE_FIGHT_CHECK_RESPOND = 11110

C_MANOR_CLEAR_THIEF_FIGHT_PREPARE_REQUEST = 11111
C_MANOR_CLEAR_THIEF_FIGHT_PREPARE_RESPOND = 11112

C_MANOR_CLEAR_THIEF_FIGHT_CHECK_REQUEST = 11113
C_MANOR_CLEAR_THIEF_FIGHT_CHECK_RESPOND = 11114

C_MANOR_STEAL_REQUEST  = 11115
C_MANOR_STEAL_RESPOND  = 11116

-- 聊天
C_JOIN_CHANNEL_REQUEST = 2001
-- [sn, name, country, guildid, chanel, ...]

C_JOIN_CHANNEL_RESPOND = 2002
-- [sn, result, info]

C_LEAVE_CHANNEL_REQUEST = 2003
-- [sn]

C_LEAVE_CHANNEL_RESPOND = 2004
-- [sn, result, info]

C_CHAT_MESSAGE_REQUEST = 2005 --聊天信息请求
 CHAT_SYSTEM = 0 
 CHAT_WORLD = 1 
 CHAT_COUNTRY = 2 
 CHAT_GUILD = 3 

--[sn, to, message]
C_CHAT_MESSAGE_RESPOND = 2006 --聊天信息返回
--[sn, result, info]

C_CHAT_MESSAGE_NOTIFY = 2007 --聊天信息通知
--[sn, [fromid, fromname], to, message]

C_QUERY_CHAT_MESSAGE_REQUEST = 2008 -- 查询聊天信息请求
-- {sn, rid}
C_QUERY_CHAT_MESSAGE_RESPOND = 2009 -- 查询聊天信息返回
--[sn, result, list]

S_CHAT_MESSAGE_REQUEST = 2900 -- 系统发送聊天信息
-- ChatMessageRequest

S_CHAT_MESSAGE_RESPOND = 2901 -- 系统发送聊天信息
-- ChatMessageRespond

S_RECORD_NOTIRY_MESSAGE_REQUEST = 2902 -- 发送离线通知请求
-- RecordNotifyMessageRequest

S_RECORD_NOTIRY_MESSAGE_RESPOND = 2903 -- 发送离线通知返回
-- RecordNotifyMessageRespond

S_TIMING_NOTIFY_ADD_REQUEST = 2904 -- 增 计时广播
S_TIMING_NOTIFY_ADD_RESPOND = 2905

S_TIMING_NOTIFY_QUERY_REQUEST = 2906 -- 查 计时广播
S_TIMING_NOTIFY_QUERY_RESPOND = 2907

S_TIMING_NOTIFY_DEL_REQUEST = 2908 -- 删 计时广播
S_TIMING_NOTIFY_DEL_RESPOND = 2909

S_ADMIN_ADD_MAIL_REQUEST = 2910		-- 填加邮件
S_ADMIN_ADD_MAIL_RESPOND = 2911

S_ADMIN_QUERY_MAIL_REQUEST = 2912	-- 查询邮件
S_ADMIN_QUERY_MAIL_RESPOND = 2913	-- 查询邮件

S_ADMIN_DEL_MAIL_REQUEST = 2914		-- 删除邮件
S_ADMIN_DEL_MAIL_RESPOND = 2915		-- 删除邮件

S_CHANNEL_MESSAGE_REQUEST = 2916
-- ChannelMessageRequest 

S_CHANNEL_MESSAGE_RESPOND = 2917
-- aGameRespond;

S_CHANGE_CHAT_CHANNEL_REQUEST = 2918           -- 改变频道
-- ChangeChatChannelRequest

S_CHANGE_CHAT_CHANNEL_RESPOND = 2919		
-- aGameRespond

S_ADMIN_ADD_MULTI_MAIL_REQUEST = 2920

S_ADMIN_ADD_MULTI_MAIL_RESPOND = 2921
-- aGameRespond

-- mail
-- mail type
MAIL_TYPE_SYSTEM  =1
MAIL_TYPE_USER    =2
MAIL_TYPE_CHAT    =3
MAIL_TYPE_CHANNEL =4
MAIL_TYPE_FRIEND  =8
MAIL_TYPE_ARENA   =16

MAIL_STATUS_UNREAD = 0x01 -- 未读
MAIL_STATUS_READ = 0x02 -- 已读

C_MAIL_MIN = 5000
C_MAIL_QUERY_REQUEST = 5001 -- 查询邮件列表请求
-- [sn, type, status] 过滤器 type: 邮件类型 status 邮件状态

C_MAIL_QUERY_RESPOND = 5002 -- 查询邮件列表返回
-- [sn, result, [id, type, title, status, [fromid, fromname]], ...]

C_MAIL_GET_REQUEST = 5003 -- 获取邮件内容请求
-- [sn, id, ...]

C_MAIL_GET_RESPOND = 5004 -- 获取邮件内容返回
-- [sn, result, [id, type, title, content, [type,id,value]], ...]

C_MAIL_MARK_REQUEST = 5005 -- 标记已读/未读请求
-- [sn, [id, status], ...]

C_MAIL_MARK_RESPOND = 5006 -- 标记已读/未读返回
-- [sn, result, [id, status], ...]

C_MAIL_DEL_REQUEST = 5007 -- 删除邮件请求
-- [sn, id, ...]

C_MAIL_DEL_RESPOND = 5008 -- 删除邮件返回
-- [sn, id, ...]

C_MAIL_SEND_REQUEST = 5009 -- 发送邮件请求
-- [sn, to, type, title, content]

C_MAIL_SEND_RESPOND = 5010 -- 发送邮件返回
-- [sn, result]

C_MAIL_CONTACT_GET_REQUEST = 5011 -- 获取联系人列表请求
-- [sn]
C_MAIL_CONTACT_GET_RESPOND = 5012 -- 获取联系人列表返回
-- [sn, result, [id, type, name, online, level, rtype, sex], ...]

C_MAIL_CONTACT_ADD_REQUEST = 5013 -- 添加联系人列表请求
-- [sn, type, id]
C_MAIL_CONTACT_ADD_RESPOND = 5014 -- 添加联系人请求列表
-- [sn, type, id, type, name, online, level, rtype, sex]

C_MAIL_CONTACT_DEL_REQUEST = 5015 -- 删除联系人请求
-- [sn, id]

C_MAIL_CONTACT_DEL_RESPOND = 5016 -- 删除联系人返回
-- [sn, id]

C_MAIL_GET_NOTIRY_MESSAGE_REQUEST = 5017
-- [sn]

C_MAIL_GET_NOTIRY_MESSAGE_RESPOND = 5018
-- [sn, result]

C_MAIL_GET_NOTIRY_MESSAGE_REQUEST = 5017
-- [sn]

C_MAIL_GET_NOTIRY_MESSAGE_RESPOND = 5018
-- [sn, result]

C_MAIL_OPEN_APPENDIX_REQUEST = 5019
C_MAIL_OPEN_APPENDIX_RESPOND = 5020

C_MAIL_CONTACT_RECOMMEND_REQUEST = 5021; -- 好友请求推荐人
C_MAIL_CONTACT_RECOMMEND_RESPOND = 5022;

S_MAIL_CONTACT_GET_REQUEST = 5901 -- 查询好友列表请求
-- MailContactGetRequest 

S_MAIL_CONTACT_GET_RESPOND = 5902 -- 查询好友列表返回
-- MailContactGetRespond 

C_MAIL_ENERGE_PRESENT_REQUEST = 5023	-- 赠送精力请求
C_MAIL_ENERGE_PRESENT_RESPOND = 5024	-- 赠送精力返回

C_MAIL_ENERGE_QUERY_REQUEST = 5025      -- 赠送查询请求
C_MAIL_ENERGE_QUERY_RESPOND = 5026      -- 赠送查询返回

NOTIFY_PRESENT = 5027

C_MAIL_PRESENT_QUERY_REQUEST = 5029
C_MAIL_PRESENT_QUERY_RESPOND = 5030

C_MAIL_RECEIVE_PRESENT_REQUEST = 5031		-- 领取赠送的奖励
C_MAIL_RECEIVE_PRESENT_RESPOND = 5032	

S_SET_PLAYER_STATUS_REQUEST = 3014	-- 禁言和封号
S_SET_PLAYER_STATUS_RESPOND = 3015	


S_MAIL_ENERGE_PRESENT_NOTIFY = 5033	
S_MAIL_ADD_FRIEND_NOTIFY = 5034

S_QUERY_RESENT_RECORD_REQUEST = 5035	
S_QUERY_RESENT_RECORD_RESPOND = 5036

C_MAIL_CONTACT_GET_BY_TYPE_REQUEST = 5037
C_MAIL_CONTACT_GET_BY_TYPE_RESPOND = 5038

C_MAIL_QUERY_PLAYER_ONLINE_STAT_REQUEST = 5039
C_MAIL_QUERY_PLAYER_ONLINE_STAT_RESPOND = 5040

C_MAIL_DELETE_RECORD_REQUEST = 5041
C_MAIL_DELETE_RECORD_RESPOND = 5042	

C_QUERY_FAVOR_REQUEST = 5043 -- 查询好感度
C_QUERY_FAVOR_RESPOND = 5044 

S_NOTIFY_AI_LOGIN_CHAT = 5045
S_NOTIFY_AI_LOGOUT_CHAT = 5046

S_ADD_FAVOR_NOTIFY = 5047

C_FAVOR_CHANGER_NOTIFY = 5048

C_QUERY_GIFT_LIST_REQUEST = 5049
C_QUERY_GIFT_LIST_RESPOND = 5050

C_PRESENT_GIFT_REQUEST = 5051
C_PRESENT_GIFT_RESPOND = 5052

-------------------------------------------------------------------------
-- fight server

-- FIGHT
C_FIGHT_PREPARE_REQUEST = 16001 -- 准备战斗
-- [sn, target, npc]
C_FIGHT_PREPARE_RESPOND = 16002 
-- [sn, result, id, data]

C_FIGHT_OPT_REQUEST = 16003 -- 战斗操作
-- [sn, id, data]
C_FIGHT_OPT_RESPOND = 16004 
-- [sn, result]

C_FIGHT_CHECK_REQUEST = 16005 -- 验证战斗
-- [sn, id, data]
C_FIGHT_CHECK_RESPOND = 16006 
-- [sn, result, rewards]

C_FIGHT_PVP_REQUEST = 16007 -- 决斗
-- [sn, pid, id]
C_FIGHT_PVP_RESPOND = 16008 
-- [sn, result]

-- in team
C_FIGHT_SYNC_REQUEST = 16040  -- {sn, type, data}
C_FIGHT_SYNC_RESPOND = 16041  -- {sn, result}

C_TEAM_DRAW_NPC_REWARD_REQUEST = 16062 -- {sn, fight_id, reward_pos}
C_TEAM_DRAW_NPC_REWARD_RESPOND = 16063

C_TEAM_QUERY_NPC_ROLL_COUNT_REQUEST = 16064
C_TEAM_QUERY_NPC_ROLL_COUNT_RESPOND = 16065 

C_TEAM_QUERY_PLAYER_FIGHT_WIN_COUNT_REQUEST = 16066 -- {sn, {fight_id,...}}
C_TEAM_QUERY_PLAYER_FIGHT_WIN_COUNT_RESPOND = 16067

C_TEAM_QUERY_TEAM_PROGRESS_REQUEST = 16068 -- {sn , teamid, {fight_id, ...}}
C_TEAM_QUERY_TEAM_PROGRESS_RESPOND = 16069

C_TEAM_START_FIGHT_REQUEST = 16070 -- {sn, fight_id}
C_TEAM_START_FIGHT_RESPOND = 16071

C_TEAM_QUERY_NPC_REWARD_REQUEST = 16072
C_TEAM_QUERY_NPC_REWARD_RESPOND = 16073

C_TEAM_QUERY_ROLL_GAME_INFO_REQUEST = 16074
C_TEAM_QUERY_ROLL_GAME_INFO_RESPOND = 16075

C_TEAM_ROLL_GAME_ROLL_REQUEST = 16076
C_TEAM_ROLL_GAME_ROLL_RESPOND = 16077

C_TEAM_RESET_TEAM_PROGRESS_REQUEST = 16084 -- {sn , teamid, {fight_id, ...}}
C_TEAM_RESET_TEAM_PROGRESS_RESPOND = 16085 

C_TEAM_FIND_NPC_REQUEST = 16086 
C_TEAM_FIND_NPC_RESPOND = 16087 

C_TEAM_BATTLE_START_REQUEST = 16200;
C_TEAM_BATTLE_START_RESPOND = 16201;

C_TEAM_BATTLE_INTERACT_REQUEST = 16202;
C_TEAM_BATTLE_INTERACT_RESPOND = 16203;

C_TEAM_BATTLE_QUERY_INFO_REQUEST = 16204;
C_TEAM_BATTLE_QUERY_INFO_RESPOND = 16205;

---------------------------------------------------------------------------
S_TEAM_CREATE_REQUEST = 18200 
S_TEAM_CREATE_RESPOND = 18201

S_TEAM_LEAVE_REQUEST = 18202 
S_TEAM_LEAVE_RESPOND = 18203

S_NOTIFY_AI_TEAM_PLAYER_ENTER_REQUEST = 18224
S_NOTIFY_AI_TEAM_PLAYER_ENTER_RESPOND = 18225

S_TEAM_INPLACE_CHECK_REQUEST = 18228
S_TEAM_INPLACE_CHECK_RESPOND = 18229

S_TEAM_INPLACE_READY_REQUEST = 18230
S_TEAM_INPLACE_READY_RESPOND = 18231

S_NOTIFY_AI_TEAM_PLAYER_READY_REQUEST = 18232
S_NOTIFY_AI_TEAM_PLAYER_READY_RESPOND = 18233

S_TEAM_QUERY_INFO_REQUEST = 18242
S_TEAM_QUERY_INFO_RESPOND = 18243

S_TEAM_SET_AUTO_CONFIRM_REQUEST = 18244
S_TEAM_SET_AUTO_CONFIRM_RESPOND = 18245

S_TEAM_SYNC_REQUEST = 18246
S_TEAM_SYNC_RESPOND = 18247

S_TEAM_DISSOLVE_REQUEST = 18256
S_TEAM_DISSOLVE_RESPOND = 18257

S_AI_TEAM_AUTOMATCH_REQUEST = 18258
S_AI_TEAM_AUTOMATCH_RESPOND = 18259

S_AI_AUTOMATCH_REQUEST  = 18260
S_AI_AUTOMATCH_RESPOND = 18261

S_GET_AUTOMATCH_TEAM_COUNT_REQUEST = 18262
S_GET_AUTOMATCH_TEAM_COUNT_RESPOND = 18263

S_NOTIFY_AI_TEAM_INPLACE_CHECK = 18266
S_NOTIFY_AI_TEAM_LEADER_CHANGE = 18268
S_NOTIFY_AI_TEAM_GROUP_CHANGE = 18270

C_TEAM_APPLY_TO_BE_LEADER_REQUEST = 18272 
C_TEAM_APPLY_TO_BE_LEADER_RESPOND = 18273

C_TEAM_VOTE_REQUEST = 18274 
C_TEAM_VOTE_RESPOND = 18275

NOTIFY_TEAM_APPLY_TO_BE_LEADER = 18276 
NOTIFY_TEAM_VOTE = 18278 
NOTIFY_TEAM_VOTE_FINISH = 18280 

S_NOTIFY_ACTIVE_AI = 18281

S_TEAM_GET_PLAYER_AI_RATIO_REQUEST = 18282
S_TEAM_GET_PLAYER_AI_RATIO_RESPOND = 18283

S_TEAM_VOTE_REQUEST = 18284
S_NOTIFY_AI_PLAYER_APPLY_TO_BE_LEADER = 18285

C_GM_MEMBER_LEAVE_REQUEST = 18286
C_GM_MEMBER_LEAVE_RESPOND = 18287

S_NOTIFY_AI_TEAM_AUTO_MATCH_CHANGE = 18288

NOTIFY_TEAM_PLAYER_AFK = 18289
NOTIFY_TEAM_PLAYER_BACK_TO_TEAM = 18290

C_TEAM_AFK_REQUEST = 18292
C_TEAM_AFK_RESPOND = 18293

C_TEAM_BACK_TO_TEAM_REQUEST = 18294
C_TEAM_BACK_TO_TEAM_RESPOND = 18295

S_NOTIFY_AI_TEAM_PLAYER_AFK = 18296
S_NOTIFY_AI_TEAM_PLAYER_BACK_TO_TEAM = 18297

--S_NOTIFY_TEAM_MEMBERS = 18298

---------------------------------------------------------------------------
S_TEAM_START_ACTIVITY_FIGHT_REQUEST = 16134
S_TEAM_START_ACTIVITY_FIGHT_RESPOND = 16135

S_TEAM_FIGHT_READY_REQUEST = 16136
S_TEAM_FIGHT_READY_RESPOND = 16137

S_NOTIFY_AI_TEAM_FIGHT_FINISH_REQUEST = 16138
S_NOTIFY_AI_TEAM_FIGHT_FINISH_RESPOND = 16139

S_NOTIFY_AI_TEAM_PLAYER_LEAVE_REQUEST = 16140
S_NOTIFY_AI_TEAM_PLAYER_LEAVE_RESPOND = 16141

S_NOTIFY_ROLL_GAME_CREATE = 16148

S_TEAM_ROLL_REWARD_REQUEST = 16150
S_TEAM_ROLL_REWARD_RESPOND = 16151

S_TEAM_GET_TEAM_PROGRESS_REQUEST = 16152
S_TEAM_GET_TEAM_PROGRESS_RESPOND = 16153

S_TEAM_FIND_NPC_REQUEST = 16154
S_TEAM_FIND_NPC_RESPOND = 16155

S_NOTIFY_AI_TEAM_FIGHT_START = 16164

S_BOUNTY_START_REQUEST = 16171
S_BOUNTY_START_RESPOND = 16172

S_BOUNTY_FIGHT_REQUEST = 16173
S_BOUNTY_FIGHT_RESPOND = 16174

S_BOUNTY_QUERY_REQUEST = 16175
S_BOUNTY_QUERY_RESPOND = 16176

S_NOTIFY_AI_BOUNTY_CHANGE = 16178

S_NOTIFY_AI_SERVICE_RESTART = 16180	

S_NOTIFY_ROLL_GAME_FINISH = 16182

S_TEAM_CHANGE_LEADER_REQUEST = 16183
S_TEAM_CHANGE_LEADER_RESPOND = 16184


-- roll game
NOTIFY_TEAM_NPC_REWARD_DROP = 16008 -- {fight_id, reward_pos, valid_time}
NOTIFY_TEAM_FIGHT_REWARD_GET = 16009 -- {[type, id, value]}
NOTIFY_TEAM_STATUS_CHANGE = 16011  
NOTIFY_TEAM_ROLL_GAME_CREATE = 16033 
NOTIFY_TEAM_PLAYER_ROLL = 16034
NOTIFY_TEAM_PLAYER_GET_PUBLIC_ROLL_REWARD = 16035

NOTIFY_FIGHT_SYNC    = 16040  -- {tye, data}
NOTIFY_TEAM_FIND_NPC = 16041

S_PVP_FIGHT_PREPARE_REQUEST = 16042;
S_PVP_FIGHT_PREPARE_RESPOND = 16043;

S_PVP_FIGHT_CHECK_REQUEST = 16044;
S_PVP_FIGHT_CHECK_RESPOND = 16045;

S_PVP_FIGHT_CHECK_NOTIFY = 16046

NOTIFY_TEAM_PROGRESS_CHANGE = 16048

S_FIGHT_PREPARE_REQUEST = 16050
S_FIGHT_PREPARE_RESPOND = 16051

S_FIGHT_CHECK_REQUEST = 16052
S_FIGHT_CHECK_RESPOND = 16053

C_QUERY_ACTIVITY_REWARD_REQUEST = 16954
C_QUERY_ACTIVITY_REWARD_RESPOND = 16955

S_ADD_ACTIVITY_REWARD_NOTIFY = 16956
C_ADD_ACTIVITY_REWARD_NOTIFY = 16957


S_TEAM_FIGHT_START_REQUEST = 16958
S_TEAM_FIGHT_START_RESPOND = 16959

S_TEAM_QUERY_BATTLE_TIME_REQUEST = 16960
S_TEAM_QUERY_BATTLE_TIME_RESPOND = 16961

S_TEAM_ENTER_BATTLE_REQUEST = 16962
S_TEAM_ENTER_BATTLE_RESPOND = 16963

S_NOTIFY_AI_BATTLE_TIME_CHANGE = 16964

C_FIGHT_QUERY_AUTO_FIGHT_RECORD_REQUEST = 16966
C_FIGHT_QUERY_AUTO_FIGHT_RECORD_RESPOND = 16967

-- map
C_MAP_MOVE_REQUEST = 18042 -- {sn, x, y, mid}
C_MAP_MOVE_RESPOND = 18043 -- {sn, result, {{pid,x,y}, ...}};

C_MAP_QUERY_PLAYER_INFO_REQUEST = 18044
C_MAP_QUERY_PLAYER_INFO_RESPOND = 18045

C_MAP_NOTIFY_SYNC_REQUEST = 18046
C_MAP_NOTIFY_SYNC_RESPOND = 18047

NOTIFY_MAP_MOVE = 16042 -- {pid,x,y}
NOTIFY_MAP_SYNC = 16043


S_MAP_MOVE_REQUEST = 18050
S_MAP_MOVE_RESPOND = 18051

S_MAP_QUERY_POS_REQUEST = 18052
S_MAP_QUERY_POS_RESPOND = 18053

S_MAP_LOGIN_REQUEST = 18054
S_MAP_LOGIN_RESPOND = 18055

S_MAP_LOGOUT_REQUEST = 18056
S_MAP_LOGOUT_RESPOND = 18057

C_TEAM_QUERY_REQUEST = 18110 -- {sn}
C_TEAM_QUERY_RESPOND = 18111 -- {sn, result, {teamid, group, leader_pid, auto_confirm, {{pid,pos,level,name,{h1,h2,h3,h4,h5}}, ...}}, {{pid,level,name}, ...}}

C_TEAM_QUERY_LIST_REQUEST = 18112 -- {sn, group}
C_TEAM_QUERY_LIST_RESPOND = 18113 -- {sn, result, {{id,group,member_count,leader_pid,leader_name}, ...}}

C_TEAM_CREATE_REQUEST = 18114 -- {sn, group}
C_TEAM_CREATE_RESPOND = 18115 -- {sn, result, {teamid, group, leader_pid, auto_confirm, {{pid,pos,level,name,{h1,h2,h3,h4,h5}}, ...}}, {}}

C_TEAM_JOIN_REQUEST = 18116 -- {sn, teamid}
C_TEAM_JOIN_RESPOND = 18117 -- {sn, result}

C_TEAM_JOIN_CONFIRM_REQUEST = 18118 -- {sn, pid}
C_TEAM_JOIN_CONFIRM_RESPOND = 18119 -- {sn, result}

C_TEAM_KICK_REQUEST = 18120 -- {sn, pid}
C_TEAM_KICK_RESPOND = 18121 -- {sn, result}

C_TEAM_CHAT_REQUEST = 18122 -- {sn, type, msg}
C_TEAM_CHAT_RESPOND = 18123 -- {sn, result}

C_TEAM_AUTO_CONFIRM_REQUEST = 18124 -- {sn, auto}
C_TEAM_AUTO_CONFIRM_RESPOND = 18125 -- {sn, result}

C_TEAM_WATCH_GROUP_REQUEST = 18126 -- {sn, group}
C_TEAM_WATCH_GROUP_RESPOND = 18127 -- {sn, result}

C_TEAM_DELETE_JOIN_REQUEST_LIST_REQUEST = 18150
C_TEAM_DELETE_JOIN_REQUEST_LIST_RESPOND = 18151

C_TEAM_INVITE_REQUEST = 18152
C_TEAM_INVITE_RESPOND = 18153

C_TEAM_PLAYER_QUERY_INVITE_LIST_REQUEST = 18154
C_TEAM_PLAYER_QUERY_INVITE_LIST_RESPOND = 18155

C_TEAM_PLAYER_REPLY_INVITATION_REQUEST = 18156
C_TEAM_PLAYER_REPLY_INVITATION_RESPOND = 18157

C_TEAM_PLAYER_AUTO_MATCH_REQUEST = 18158
C_TEAM_PLAYER_AUTO_MATCH_RESPOND = 18159

C_TEAM_AUTO_MATCH_REQUEST = 18160
C_TEAM_AUTO_MATCH_RESPOND = 18161

C_TEAM_CHANGE_GROUP_REQUEST = 18178
C_TEAM_CHANGE_GROUP_RESPOND = 18179

C_TEAM_CHANGE_LEADER_REQUEST = 18180
C_TEAM_CHANGE_LEADER_RESPOND = 18181

C_TEAM_QUERY_INFO_BY_PID_REQUEST = 18182
C_TEAM_QUERY_INFO_BY_PID_RESPOND = 18183

C_TEAM_CHANGE_LEVEL_LIMIT_REQUEST = 18184
C_TEAM_CHANGE_LEVEL_LIMIT_RESPOND = 18185

S_QUERY_AUTOMATCH_TEAM_REQUEST = 16187
S_QUERY_AUTOMATCH_TEAM_RESPOND = 16188

S_NOTIFY_AI_NEW_JOIN_REQUEST = 16189
S_TEAM_JOIN_CONFIRM_REQUEST = 16190

-- prepare
C_TEAM_INPLACE_CHECK_REQUEST = 18130  -- {sn}
C_TEAM_INPLACE_CHECK_RESPOND = 18131  -- {sn, result}

C_TEAM_INPLACE_READY_REQUEST = 18132  -- {sn}
C_TEAM_INPLACE_READY_RESPOND = 18133  -- {sn, result}

-- in fight
C_TEAM_SYNC_REQUEST = 18140  -- {sn, type, data}
C_TEAM_SYNC_RESPOND = 18141  -- {sn, result}


NOTIFY_TEAM_PLAYER_JOIN_REQUEST = 18101  -- {pid, level, name}
NOTIFY_TEAM_PLAYER_JOIN = 18102  -- {pid, pos, level, name, {h1,h2,h3,h4,h5}}
NOTIFY_TEAM_PLAYER_LEAVE = 18103  -- {pid}
NOTIFY_TEAM_PLAYER_CHAT = 18104  -- {pid, type, msg}
NOTIFY_TEAM_CHANGE_LEADER = 18105  -- {pid, auto_confirm}
NOTIFY_TEAM_CHANGE = 18106  -- {id,group,member_count,leader_pid,leader_name}
NOTIFY_TEAM_PLAYER_INVITE_LIST_CHANGE = 18107
NOTIFY_TEAM_GROUP_CHANGE  = 18110
NOTIFY_TEAM_LEVEL_LIMIT_CHANGE = 18111
NOTIFY_TEAM_INPLACE_CHECK = 18130  -- {}
NOTIFY_TEAM_INPLACE_READY = 18132  -- {pid}
NOTIFY_TEAM_SYNC          = 18140  -- {tye, data}
NOTIFY_TEAM_AUTO_MATCH = 18160

-- 悬赏
C_BOUNTY_QUERY_REQUEST = 16090 -- {sn, result, quest, record, next_fight_time}
C_BOUNTY_QUERY_RESPOND = 16091

C_BOUNTY_START_REQUEST = 16092 -- {sn, result, quest, next_fight_time}
C_BOUNTY_START_RESPOND = 16093 

C_BOUNTY_CANCEL_REQUEST = 16094 -- {sn, result}
C_BOUNTY_CANCEL_RESPOND = 16095

C_BOUNTY_FIGHT_REQUEST = 16096 -- {sn, result, next_fight_time}
C_BOUNTY_FIGHT_RESPOND = 16097

NOTIFY_BOUNTY_TEAM_CHANGE   = 16090 -- {quest, record, next_fight_time}
NOTIFY_BOUNTY_PLAYER_CHANGE = 16091 -- {normal, double}



C_DEFEND_STRONGHOLD_REQUEST = 16101
C_DEFEND_STRONGHOLD_RESPOND = 16102

C_DEFEND_RESOURCE_REQUEST = 16103
C_DEFEND_RESOURCE_RESPOND = 16104

C_DEFEND_STRENGTHEN_REQUEST = 16105
C_DEFEND_STRENGTHEN_RESPOND = 16106
	
C_DEFEND_EXCHANGE_REQUEST = 16107
C_DEFEND_EXCHANGE_RESPOND = 16108

C_DEFEND_ATTRACT_REQUEST = 16109
C_DEFEND_ATTRACT_RESPOND = 16110

C_DEFEND_MOVE_REQUEST = 16111
C_DEFEND_MOVE_RESPOND = 16112

C_DEFEND_REWARD_REQUEST = 16113
C_DEFEND_REWARD_RESPOND = 16114


NOTIFY_RESOURCE_CHANGE = 16115
NOTIFY_BOSS_MOVE = 16116
NOTIFY_GAME_OVER = 16117
NOTIFY_PLAYER_MOVE = 16118
NOTIFY_SITE_CHANGE = 16119
NOTIFY_COME_IN = 16120

C_DEFEND_BOX_REQUEST = 16121
C_DEFEND_BOX_RESPOND = 16122

C_DEFEND_FIX_SITE_REQUEST = 16123
C_DEFEND_FIX_SITE_RESPOND = 16124

C_DEFEND_FIGHT_END_REQUEST = 16125
C_DEFEND_FIGHT_END_RESPOND = 16126

C_DEFEND_BEGIN_REQUEST = 16127
C_DEFEND_BEGIN_RESPOND = 16128

C_DEFEND_QUERY_REQUEST = 16129
C_DEFEND_QUERY_RESPOND = 16130

C_FISH_MAKE_TEAM_REQUEST = 16231
C_FISH_MAKE_TEAM_RESPOND = 16232

C_FISH_TEAM_INFO_REQUEST = 16233
C_FISH_TEAM_INFO_RESPOND = 16234

C_FISH_TEAM_LEADER_REQUEST = 16235
C_FISH_TEAM_LEADER_RESPOND = 16236

C_INVITE_PLAYER_REQUEST = 16237
C_INVITE_PLAYER_RESPOND = 16238

C_INVITATION_ANSWER_REQUEST = 16239
C_INVITATION_ANSWER_RESPOND = 16240

C_FISH_BUY_BAIT_REQUEST = 16241
C_FISH_BUY_BAIT_RESPOND = 16242

C_FISH_BEGIN_REQUEST = 16243
C_FISH_BEGIN_RESPOND = 16244

C_FISH_END_REQUEST = 16245
C_FISH_END_RESPOND = 16246

C_FISH_ASSIST_REQUEST = 16247
C_FISH_ASSIST_RESPOND = 16248

C_FISH_FIGHT_CHECK_REQUEST = 16249
C_FISH_FIGHT_CHECK_RESPOND = 16250

C_FISH_STATUS_REQUEST = 16251
C_FISH_STATUS_RESPOND = 16252

C_FISH_RANK_LIST_REQUEST = 16253
C_FISH_RANK_LIST_RESPOND = 16254

C_QUIT_REQUEST = 16255
C_QUIT_RESPOND = 16256

C_QTE_CHECK_REQUEST = 16257
C_QTE_CHECK_RESPOND = 16258

C_QUERY_ROOM_REQUEST = 16259
C_QUERY_ROOM_RESPOND = 16260

NOTIFY_KICK = 16271
NOTIFY_INVITE = 16272
NOTIFY_JOIN = 16273
NOTIFY_FISH = 16274
NOTIFY_ASSIST = 16275
NOTIFY_FIGHT = 16276
NOTIFY_PLAYER_STATUS = 16277
NOTIFY_PLAYER_QUIT = 16278
NOTIFY_NEED_HELP = 16279
NOTIFY_MAKE_TEAM = 16280

C_TEAM_QUERY_BATTLE_TIME_REQUEST = 16281
C_TEAM_QUERY_BATTLE_TIME_RESPOND = 16282

C_TEAM_ENTER_BATTLE_REQUEST = 16283
C_TEAM_ENTER_BATTLE_RESPOND = 16284


--quiz
C_QUIZ_DAILY_QUERY_INFO_REQUEST = 17014
C_QUIZ_DAILY_QUERY_INFO_RESPOND = 17015

C_QUIZ_DAILY_ANSWER_REQUEST = 17016
C_QUIZ_DAILY_ANSWER_RESPOND = 17017

C_QUIZ_DAILY_DRAW_REWARD_REQUEST = 17018
C_QUIZ_DAILY_DRAW_REWARD_RESPOND = 17019

C_QUIZ_DAILY_SEEK_HELP_REQUEST = 17020
C_QUIZ_DAILY_SEEK_HELP_RESPOND = 17021

C_QUIZ_WEEKLY_MATCH_REQUEST = 17023
C_QUIZ_WEEKLY_MATCH_RESPOND = 17024

C_QUIZ_WEEKLY_CANCEL_MATCH_REQUEST = 17025
C_QUIZ_WEEKLY_CANCEL_MATCH_RESPOND = 17026

C_QUIZ_WEEKLY_QUERY_REQUEST = 17027
C_QUIZ_WEEKLY_QUERY_RESPOND = 17028

C_QUIZ_WEEKLY_GET_TYPE_REQUEST = 17029
C_QUIZ_WEEKLY_GET_TYPE_RESPOND = 17030

C_QUIZ_WEEKLY_ANSWER_REQUEST = 17031
C_QUIZ_WEEKLY_ANSWER_RESPOND = 17032

NOTIFY_QUIZ_DISPATCH = 17033
NOTIFY_QUIZ_END = 17034
NOTIFY_QUIZ_MATCH = 17035
NOTIFY_QUIZ_ANSWER = 17036

C_QUIZ_WEEKLY_TOTAL_COUNT_REQUEST = 17037
C_QUIZ_WEEKLY_TOTAL_COUNT_RESPOND = 17038

C_QUIZ_WORLD_QUERY_INFO_REQUEST = 17039
C_QUIZ_WORLD_QUERY_INFO_RESPOND = 17040

C_QUIZ_WORLD_ANSWER_REQUEST = 17041
C_QUIZ_WORLD_ANSWER_RESPOND = 17042

WORLD_QUIZ_DISPATCH_NOTIFY = 17043
WORLD_QUIZ_GAME_OVER_NOTIFY = 17044

WORLD_QUIZ_ANSWER_NOTIFY = 17045

C_ADD_GROUP_SCORE_REQUEST = 17047

C_GROUP_SCORE_REQUEST = 17049
C_GROUP_SCORE_RESPOND = 17050


------------------------ 后宫相关协议
C_BACKYARD_MODIFYNAME_REQUEST = 17051       -- 修改名字
C_BACKYARD_MODIFYNAME_RESPOND = 17052

C_BACKYARD_DIANZAN_REQUEST = 17053  -- 点赞
C_BACKYARD_DIANZAN_RESPOND = 17054

C_BACKYARD_GOODSPURCHASE_REQUEST = 17055 -- 购买商品
C_BACKYARD_GOODSPURCHASE_RESPOND = 17056

C_BACKYARD_EXPANDBUILD_REQUEST = 17057  -- 扩建
C_BACKYARD_EXPANDBUILD_RESPOND = 17058

C_BACKYARD_HOLDFURNITURE_REQUEST = 17059 -- 保存家具
C_BACKYARD_HOLDFURNITURE_RESPOND = 17060

C_BACKYARD_ACQUIREFURNITURE_REQUEST = 17061 --获得家具(方式很多，不局限于购买)
C_BACKYARD_ACQUIREFURNITURE_RESPOND = 17062

C_BACKYARD_DELETEFURNITURE_REQUEST = 17063 -- 移除家具
C_BACKYARD_DELETEFURNITURE_REQUEST = 17064

C_BACKYARD_CLEARFURNITURE_REQUEST = 17065 -- 清楚家具
C_BACKYARD_CLEARFURNITURE_RESPOND = 17066

C_BACKYARD_UNLOCKGOODFEELSLOT_REQUEST = 17067 -- 开启妖精培养槽
C_BACKYARD_UNLOCKGOODFEELSLOT_RESPOND = 17068

C_BACKYARD_ADDFAIRYTOSLOT_REQUEST = 17069 -- 妖精放置培养槽
C_BACKYARD_ADDFAIRYTOSLOT_RESPOND = 17070

C_BACKYARD_ENTERBACKYARD_REQUEST = 17071 -- 进入后宫
C_BACKYARD_ENTERBACKYARD_RESPOND = 17072

C_BACKYARD_REMOVEFAIRYFROMSLOT_REQUEST = 17073 -- 移除妖精
C_BACKYARD_REMOVEFAIRYFROMSLOT_RESPOND = 17074

C_BACKYARD_QUERYFAIRYGOODFEEL_REQUEST = 17075 -- 查询妖精好感度
C_BACKYARD_QUERYFAIRYGOODFEEL_RESPOND = 17076

-----------------------------------------

C_PLAYERPROPERTY_QUERY_REQUEST = 17081 --查询玩家属性
C_PLAYERPROPERTY_QUERY_RESPOND = 17082
C_PLAYERPROPERTY_MODIFY_REQUEST = 17083--设置玩家属性
C_PLAYERPROPERTY_MODIFY_RESPOND = 17084

S_PLAYERPROPERTY_QUERY_REQUEST = 17085 
S_PLAYERPROPERTY_QUERY_RESPOND = 17086

S_PLAYERPROPERTY_MODIFY_REQUEST = 17087
S_PLAYERPROPERTY_MODIFY_RESPOND = 17088

C_MWHJ_PROPERTY_QUERY_REQUEST = 17089
C_MWHJ_PROPERTY_QUERY_RESPOND = 17090

C_MWHJ_PROPERTY_MODIFY_REQUEST = 17091
C_MWHJ_PROPERTY_MODIFY_RESPOND = 17092

C_RANKLIST_QUERY_PLAYER_RANK_REQUEST = 17101
C_RANKLIST_QUERY_PLAYER_RANK_RESPOND = 17102

C_RANKLIST_QUERY_TEAM_RANK_REQUEST = 17103
C_RANKLIST_QUERY_TEAM_RANK_RESPOND = 17104

C_RANKLIST_REWARD_REQUEST = 17105
C_RANKLIST_REWARD_RESPOND = 17106

S_RANKLIST_UPDATE_DATUM_REQUEST = 17107
S_RANKLIST_UPDATE_DATUM_RESPOND = 17108

--SERVER------------------
S_TRADE_WITH_SYSTEM_REQUEST = 1904
S_TRADE_WITH_SYSTEM_RESPOND = 1905
S_GET_PLAYER_INFO_REQUEST = 3004 -- PGetPlayerInfoRequest
S_GET_PLAYER_INFO_RESPOND = 3005 -- PGetPlayerInfoRespond
S_ADD_PLAYER_NOTIFICATION_REQUEST = 3006 -- PAddPlayerNotificationRequest
S_ADD_PLAYER_NOTIFICATION_RESPOND = 3007 -- PAddPlayerNotificationRespond
S_ADMIN_REWARD_REQUEST = 3008 --PAdminRewardRequest
S_ADMIN_REWARD_RESPOND = 3009 --PAdminAddExpRespond
S_GET_PLAYER_HERO_INFO_REQUEST = 3010 -- PGetPlayerHeroInfoRequest
S_GET_PLAYER_HERO_INFO_RESPOND = 3011 -- PGetPlayerHeroInfoRespond

S_QUERY_UNACTIVE_AI_REQUEST = 1028  -- PQueryUnactiveAIRequest
S_QUERY_UNACTIVE_AI_RESPOND = 1029  -- PQUeryUnactiveAIRespond

S_UPDATE_AI_ACTIVE_TIME_REQUEST = 1030
S_UPDATE_AI_ACTIVE_TIME_RESPOND = 1031

S_CHANGE_AI_NICK_NAME_REQUEST = 1032
S_CHANGE_AI_NICK_NAME_RESPOND = 1033

S_ADMIN_PLAYER_KICK_REQUEST = 3016
S_ADMIN_PLAYER_KICK_RESPOND = 3017

S_CHANGE_BUFF_REQUEST = 3018--PChangeBuffRequest
S_CHANGE_BUFF_RESPOND = 3019--aGameRespond
-------------------------

--REASON----------------
REASON_OPEN_GIFT_BAG       = 2028 -- 礼包消耗

REASON_GUILD_WAR_JOIN_CONSUME    = 2045 -- 军团战活动报名
REASON_GUILD_WAR_INSPIRE_CONSUME = 2046 -- 军团战鼓舞消耗
--REASON_GUILD_WAR_TEAM_REWARD     = 2047 -- 军团战混战奖励
REASON_GUILD_WAR_LEADER_REWARD   = 2048 -- 军团战军团长排名奖励
REASON_GUILD_WAR_MEMBER_REWARD   = 2049 -- 军团战军团成员排名奖励
REASON_GUILD_WAR_ORDER_REWARD    = 2050 -- 军团战PK战顺序奖励

REASON_GUILD_WAR_TEAM_REWARD   = 2054 -- 军团战混战奖励
--REASON_GUILD_WAR_TEAM_REWARD2   = 1055 -- 军团战混战奖励
--REASON_GUILD_WAR_TEAM_REWARD3   = 1056 -- 军团战混战奖励
--REASON_GUILD_WAR_TEAM_REWARD4   = 1057 -- 军团战混战奖励
--REASON_GUILD_WAR_TEAM_REWARD5   = 1058 -- 军团战混战奖励
--占用2054-2064 for 军团战奖励
REASON_GUILD_BOSS_REWARD       = 2055   --军团boss奖励 
REASON_GUILD_QUEST            = 2056    --军团任务
REASON_SHARED_QUEST            = 2057   --共享任务
REASON_GUILD_QUEST_STEP_REWARD = 2058
REASON_GUILD_QUEST_COST_ITEM   = 2059
REASON_NPC_REWARD              = 2060
REASON_INVEST_NPC              = 2061
REASON_NPC_PAYBACK_REWARD      = 2062
REASON_ADD_GUILD_ITEM          = 2263

REASON_LUCKY_DRAW_MIN = 60000 --抽奖
REASON_LUCKY_DRAW_MAX = 60499

REASON_BUY_MIN = 60500 --商店购买原因最小值
REASON_BUY_MAX = 61000 --商店购买原因最大值

REASON_LUCKY_DRAW_CHANGE_POOL = 61001 -- 抽将切换奖池

CHARGE_TYPE_GUILD_XING5          = 13001   -- 军团五行阵奖励
CONSUME_TYPE_GUILD_XING5         = 13002   -- 军团五行阵消耗
REASON_CONSUME_TYPE_GUILD_CREATE = 13003   -- 创建军团消耗
REASON_CONSUME_TYPE_PRAY_RESET = 13004     -- 重置军团祈愿
REASON_CONSUME_TYPE_GUILD_UPDATE_PRAY_PROGRESS = 13005 -- 更新军团祈愿进度
REASON_CONSUME_TYPE_GUILD_DRAW_PRAY_REWARD = 13006 -- 领取祈愿奖励
REASON_CONSUME_TYPE_GUILD_PRAY_HELP_OTHERS = 13007 -- 帮助他人完成祈愿
REASON_GUILD_EXPLORE = 13008                       -- 军团探索
REASON_GUILD_DONATE_REWARD = 13009                 -- 军团每日贡献奖励 

REASON_MANOR_MANUFACTURE_GATHER  = 11001   -- 庄园生产消耗/产出
REASON_MANOR_MANUFACTURE_LEVEL_UP = 11003  -- 庄园升级生产线消耗
REASON_MANOR_MANUFACTURE_INCREASE_POWER = 11004  --庄园提升工人体力消耗
REASON_MANOR_MANUFACTURE_INCREASE_STORAGE = 11005 --庄园提升产线临时存储上限
REASON_MANOR_MANUFACTURE_INCREASE_ORDER_LIMIT = 11006 --庄园提升订单数量上限
REASON_ARENA_REWARD        = 19001
REASON_TEAM_FIGHT_REWARD = 19002 --小队副本掉落奖励 
REASON_TEAM_ROLL_PUBLIC_REWARD = 19003 -- 小队副本公共掉落奖励
REASON_MANOR_EVENT = 19004
REASON_MANOR_TASK_STONE = 19005		-- 庄园任务刷新钻石消耗
REASON_MANOR_TASK_DONE = 19006
REASON_MANOR_STARBOX_REWARD = 19007     -- 星级宝箱奖励
REASON_MANOR_TASK_ENERGY = 19013	-- 庄园任务开始任务时消耗
REASON_MANOR_MANUFACTURE_FINISH_IMMEDIATELY = 19050  -- 生产立即完成消耗
REASON_MANOR_MANUFACTURE_UNLOCK_LINE = 19051 -- 解锁生产线
REASON_MANOR_MANUFACTURE_STEAL_OTHERS = 19052 -- 偷别人生产线的东西
REASON_MANOR_MANUFACTURE_PAY_BACK_STOLEN_GOODS = 19053 --生产线击败盗贼后返还物品
REASON_MANOR_TASK_ACHIEVE_STAR_REWARD = 19054

REASON_DAILY_QUIZ = 14028 --每日答题

REASON_DEFEND_TASK_DONE = 19007		-- 防守要塞任务结束奖励
REASON_DEFEND_AWARD = 19008

REASON_WEEK_QUIZ = 19009		-- 周答题结束奖励
REASON_PILLAGE_ARENA_REWARD = 19010  -- 掠夺竞技场奖励

REASON_TEAM_FIGHT_SCORE_REWARD = 19011 --小队副本评分奖励

REASON_RANK_ARENA_REWARD = 19012  -- 排名竞技场奖励
REASON_EXTRA_ROLL = 19013 --额外roll

REASON_TRADE = 19014 --交易行交易
REASON_RANK_ARENA_CONSUME = 19015  -- 排名竞技场消耗体力

REASON_FISH_BAIT_CONSUME = 19016	-- 钓鱼购买鱼饵消耗
REASON_FISH_HELP_REWARD = 19017		-- 钓鱼协助奖励
REASON_FISH_REWARD = 19018		-- 钓鱼奖励

REASON_CONSUME_TYPE_PLYAERPROPERTY_SET = 19019 -- 设置玩家属性物品消耗
REASON_BACKYARD_EXPANDBUILD = 19020 -- 后宫场地扩建消耗
REASON_BACKYARD_UNLOCKSLOT = 19021 -- 解锁妖精好感培养槽

REASON_ARENA_CHALLENGE = 19022
REASON_ARENA_WIN = 19023

REASON_ENERGY_PRESENT = 19024	-- 赠送时之力
REASON_FAVOR_GIFT = 19025	-- 赠送礼物增加好感度的消耗
REASON_FAVOR_GIFT2 = 19026
REASON_WORLD_BOSS = 19027	-- 世界Boss和军团boss阶段奖励
REASON_WORLD_BOSS_KILL = 19028	-- 击杀boss奖励
REASON_WORLD_BOSS_RANK = 19029	-- 排名奖励 

REASON_PVP_DROP	= 19030
REASON_PVE_DROP = 19031
REASON_TEAM_ACTIVITY = 19032
REASON_ARENA_RESET_ENEMY_LIST = 19033

GM_INTERFACE_REQUEST = 19200	-- GM 接口
GM_INTERFACE_RESPOND = 19201
